### ISSUE TITLE
dns health/api certs rotation

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1016]
### Expected behavior

* As a paas-templates operator
* In order to maintain distribution availability
* I need to manage `bosh-dns` certs rotation

### Observed behavior
`dns-recursor` deployment (which uses `bosh-dns` release) manages internal dns aliases and recurse on legacies dns server.
This deployment uses 2 MTLS certs (api and healthcheck) propagated by every root director (using `runtime-config`) to each managed deployments.

```
  jobs:
  - name: bosh-dns
    properties:
      api:
        client:
        server:
      cache:
        enabled: true
      health:
        client:
        enabled: false
        server:
      recursors:
```
Certs are managed in following credhub pathnames:
- /dns_api_tls_ca
- /dns_api_server_tls
- /dns_api_client_tls
- /dns_healthcheck_tls_ca
- /dns_healthcheck_server_tls
- /dns_healthcheck_client_tls

### Affected releases

* All since xxx `bosh-dns` release
