### ISSUE TITLE
Web UI for consumming OSB brokers in K8S

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1024]
### Expected behavior

* As a K8S user | osb service provider | paas-templates author | paas-templates maintainer
* In order to consume paas-templates OSB-based marketplace
* I need a webui to discover service definitions, service plans along with their supported params

### Observed behavior

Commercial openshift svcat UI has been removed:
* [openshift 4 deprecated its service catalog support](https://docs.openshift.com/container-platform/4.1/applications/service_brokers/installing-service-catalog.html) without a well documented migration plan.

Currently lacking stable OpenSource WebUis for K8S Service Catalog 
* KubeApps support is being deprecated https://github.com/kubeapps/kubeapps/issues/2125
* Stratos support for svcat is being considered https://github.com/cloudfoundry/stratos/issues/4787

### Possible alternatives

Use off-the-shelf WebUi for K8S API machinery support
<details>
<summary>crd</summary>
   * [CRDs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) support the following metadata
      * Name
      * Shortnames
      * plural
      * singular
      * [custom fields](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema) and associated strutural schema
      * [additionalPrinterColumns](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#additional-printer-columns): displaying CR fields 
         * Priority (0 or >0)
         * Type (integer, number, string, boolean, date)
         * Format (int32, int64, float, double, byte, date, date-time, password)
      * [SubResources](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources)
         * `/status`: with its openAPI schema
         * `/scale`: only supports `autoscaling/v1.Scale`
      * [categories](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories)
     * [Common labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

Key | Description | Example | Type
-- | -- | -- | --
app.kubernetes.io/name | The name of the application | mysql | string
app.kubernetes.io/instance | A unique name identifying the instance of an application | mysql-abcxzy | string
app.kubernetes.io/version | The current version of the application (e.g., a semantic version, revision hash, etc.) | 5.7.21 | string
app.kubernetes.io/component | The component within the architecture | database | string
app.kubernetes.io/part-of | The name of a higher level application this one is part of | wordpress | string
app.kubernetes.io/managed-by | The tool being used to manage the operation of an application | helm | string

</details>

* `Service Catalog Operator`: a CRD which watches svcat [ClusterServiceClass](https://svc-cat.io/docs/concepts/#service-resources) and create corresponding `CRD` objects, e.g. for a Mariadb-Dedicated 
   * CRD: `Mariadb-Dedicated`
      * Custom fields:
         * `plan`: valid values among `small`, `medium`, `large`
            * type: String
            * properties: oneOf  `small`, `medium`, `large`
            * description: "small plan is limited to 10 connections. medium plan to 100 connections. large to 1000 connections"
         * other service plan [service instance params](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#schemas-object) mapped
      * SubResources: `Mariadb-User` (representing service binding)
         * Custom fields:
            * other service plan [service binding params](https://github.com/openservicebrokerapi/servicebroker/blob/master
   * An controller is associated to each CRD to instanciate corresponding svcat [ServiceInstance](https://svc-cat.io/docs/resources/#serviceinstance) and [ServiceBinding](https://svc-cat.io/docs/resources/#servicebinding)
      * Possible implementation leveraging [Kubernetes Universal Declarative Operator (KUDO)](https://kudo.dev/docs/what-is-kudo.html), see [sample config in getting started](https://kudo.dev/docs/developing-operators/getting-started.html)

<details>
<summary>helm chart</summary>
   * Helm charts supports the following [metadata](https://helm.sh/docs/topics/charts/#the-chartyaml-file)

```yaml
name: The name of the chart (required)
version: A SemVer 2 version (required)
kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: A single-sentence description of this project (optional)
type: The type of the chart (optional)
keywords:
  - A list of keywords about this project (optional)
home: The URL of this projects home page (optional)
sources:
  - A list of URLs to source code for this project (optional)
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    tags: # (optional)
      - Tags can be used to group charts for enabling/disabling together
    enabled: (optional) Enabled bool determines if chart should be loaded
    import-values: # (optional)
      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
icon: A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: The version of the app that this contains (optional). This needn't be SemVer.
deprecated: Whether this chart is deprecated (optional, boolean)
annotations:
  example: A list of annotations keyed by name (optional).
```
   * [Values](https://helm.sh/docs/topics/charts/#scope-dependencies-and-values) with their associated schema. See [global values examples](https://helm.sh/docs/topics/charts/#global-values)
</details>

* `Service Catalog HelmChart Factory`: a CRD which watches svcat [ClusterServiceClass](https://svc-cat.io/docs/concepts/#service-resources) and dynamically create helmcharts and publishes them into a helm repository. e.g. for a Mariadb-Dedicated, the following chart definition maps the OSB [catalog metadata](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata)

```yaml
name: "Mariadb-Dedicated" # The name of the chart (required)
version: Osb tag mapped # A SemVer 2 version (required)
# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
description: ServiceDefinition.long_description # A single-sentence description of this project (optional)
type: The type of the chart (optional)
keywords:
  - A list of keywords about this project (optional)
home: The URL of this projects home page (optional)
sources:
  - A list of URLs to source code for this project (optional)
dependencies: # A list of the chart requirements (optional)
  - name: The name of the chart (nginx)
    version: The version of the chart ("1.2.3")
    repository: The repository URL ("https://example.com/charts") or alias ("@repo-name")
    condition: (optional) A yaml path that resolves to a boolean, used for enabling/disabling charts (e.g. subchart1.enabled )
    tags: # (optional)
      - Tags can be used to group charts for enabling/disabling together
    enabled: (optional) Enabled bool determines if chart should be loaded
    import-values: # (optional)
      - ImportValues holds the mapping of source values to parent key to be imported. Each item can be a string or pair of child/parent sublist items.
    alias: (optional) Alias to be used for the chart. Useful when you have to add the same chart multiple times
maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)
icon:  metadata.imageUrl # A URL to an SVG or PNG image to be used as an icon (optional).
appVersion: The version of the app that this contains (optional). This needn't be SemVer.
deprecated: Whether this chart is deprecated (optional, boolean)
annotations:
  example: A list of annotations keyed by name (optional).
```
* CRDs: defines `Mariadb-Dedicated` and subresource `Mariadb-User` 

### Affected releases

* 49.x
* earlier versions
