### ISSUE TITLE
Add support of service provider exposed behind legacy api gateways

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1106]
### Expected behavior

As an OSB service provider
* in order expose my service while my service broker endpoint is only reacheable through a legacy api gateway (performing URL rewrite + potentially expecting TLS client authentication)
* I need to have osb-reverse-proxy to hide such details from cloudfoundry osb cloudcontroller client (which only support [TLS endpoint expecting basic auth](https://docs.cloudfoundry.org/services/managing-service-brokers.html#register-broker), and a [path prefix](https://docs.cloudfoundry.org/services/supporting-multiple-cf-instances.html#routing-auth)

### Observed behavior

*  osb-reverse-proxy and its integration in paas-templates is lacking tests and documentation demonstrating how to configure client TLS certificate:
   * not yet clear how to deply a custom cert using ops-depls/cf-apps-deployments/osb-reverse-proxy/secrets/meta.yml supported syntax

```yaml
meta:
  osb-reverse-proxy:
    # overrides application-cloud.yml in the osb-cmdb.jar files
    # should not be required in most cases
    application_yml:
# This should be spring or spring-cloud-gateway configuration
# See https://cloud.spring.io/spring-cloud-gateway/reference/html/#configuring-route-predicate-factories-and-gateway-filter-factories
```

[spring cloud gateway tls support](https://cloud.spring.io/spring-cloud-gateway/reference/html/#tls-and-ssl)
<details>
<summary>doc extract</summary>

> The gateway can listen for requests on HTTPS by following the usual Spring server configuration. The following example shows how to do so:
> Example 57. application.yml
> 
> server:
>   ssl:
>     enabled: true
>     key-alias: scg
>     key-store-password: scg1234
>     key-store: classpath:scg-keystore.p12
>     key-store-type: PKCS12
> 
> For a production deployment, you can configure the gateway with a set of known certificates that it can trust with the following configuration:
> Example 59. application.yml
> 
> spring:
>   cloud:
>     gateway:
>       httpclient:
>         ssl:
>           trustedX509Certificates:
>           - cert1.pem
>           - cert2.pem
> 
> If the Spring Cloud Gateway is not provisioned with trusted certificates, the default trust store is used (which you can override by setting the javax.net.ssl.trustStore system property).
</details>

* osb-reverse-proxy acts as passthrough for HTTP headers including the basic auth. This might conflict with the API gateway expectation even though client TLS cert is used
* osb-reverse-proxy currently only propagates traffic with path `/v2/*` downstream. It would reject `prefix/v2/*`
https://github.com/orange-cloudfoundry/osb-reverse-proxy/blob/c3745acc531b620ee23be853e5a67f9740fd5863/src/main/java/com/orange/oss/osbreverseproxy/SecurityConfig.java#L120

### Affected releases

* 50.x
* earlier versions
