### ISSUE TITLE
some images are not pulled from k8s-jcr when gitlab is provisioned on k8s  

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1136]
### Expected behavior
* As a paas-templates operator
* In order to be confident with my platform
* I need to be able to reproduce middleware provisioning from scratch (without data in caches)

### Observed behavior
When I provision gitlab helm chart (v13.6.1) product, an image (gitlab-workhorse) can't be pulled by k8s from internal registry (k8s-jcr).
The image is not available on k8s-jcr (docker pull docker.<JCR_URL>/gitlab-org/build/cng/gitlab-workhorse-ce:v13.6.1 is KO)
The image is available on remote (docker pull registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce:v13.6.1 is OK)

### Messages
```
  containerStatuses:
  - image: registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce:v13.6.1
    imageID: ""
    lastState: {}
    name: gitlab-workhorse
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "registry.gitlab.com/gitlab-org/build/cng/gitlab-workhorse-ce:v13.6.1"
        reason: ImagePullBackOff
```

### Workaround
On k8s-jcr (administration view), click on repositories, choose Virtual/docker. 
On selected repositories, set "registry.gitlab.com" repository as the first one in the list in order to be able to pull the missing image.
