### ISSUE TITLE
COA bosh release sha1 digest error

### ISSUE THREAD

**Issue by ogrand** [orange-cloudfoundry/paas-templates#1202]
### Expected behavior
* As a paas-templates operator
* I need to deploy coab  mysql instances without errors

### Observed behavior
When deployed coab mysql instance, concourse `display` task shows previous cf-mysql release `37.0.1` with associated sha1

```
releases:
- name: cf-mysql
  version: 37.1.0
  sha1: 3bb8bbda76a045b180bc84fcec32ca59e1f578ec
```

Then in concourse `resolve-manifest-latest-versions` task, cf-mysql release is update to `38.0.0`, but sha1 doesn't change and we encoutered following error when deployed

```
Task 5024074 | 08:13:27 | Error: Expected stream to have digest '3bb8bbda76a045b180bc84fcec32ca59e1f578ec' but was '7f87ba3a839d2182295374f4a366761bb9356ab2'
```

Note that `7f87ba3a839d2182295374f4a366761bb9356ab2` sha1 is the right digest for `38.0.0`.

### Affected releases
* 51.0.2
