### ISSUE TITLE
loki promtail syslog interoperability issue with syslog-release/firehose-to-syslog

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1273]
### Expected behavior

* As a paas-templates operator
* In order to 
  * benefit from loki to collect and visualize platform logs 
* I need
 * syslog bridge from:
   * bosh syslog release
   * firehose-to-syslog cloudfoundry connector  

### Observed behavior

The promtail syslog configured refuse to ingest syslog:

```
level=warn ts=2021-09-07T09:29:27.165098581Z caller=syslogtarget.go:171 msg="error parsing syslog stream" err="expecting a version value in the range 1-999 [col 3]" 
```

### references

- https://github.com/orange-cloudfoundry/paas-templates/issues/686
- https://github.com/orange-cloudfoundry/paas-templates/issues/1027

 
### Affected releases

* 52.x

**Comment by poblin-orange** [comment]
syslog-release configuration enabled vm level log collection:
```
- type: replace
  path: /addons/-
  value:
    name: syslog
    jobs:
    - name: syslog_forwarder
      release: syslog
      properties:
        syslog:
          director: micro-bosh
          address: supervision-syslog-vip.internal.paas
          port: 5514
          transport: tcp
          heuristically_filter_debug_messages: true
        logging:
          format:
            timestamp: rfc3339 #Format for timestamp in log file forwarder logs. Valid values are 'deprecated' and 'rfc3339'

```
