### ISSUE TITLE
Improve reverse engineering core connectivity routes

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1300]
### Expected behavior

* As a paas-templates operator 
* In order to reverse engineering traffic routing (e.g. private-s3.internal.paas)
> "http://private-s3.internal.paas:9000/bosh-releases/cloudfoundry/bosh-271.8.0.tgz": read tcp 10.254.1.114:54898->192.168.116.19:9000: read: connection reset by peer
* I need to be able to quickly discover routing rules associated with a published route
   * on production systems
   * in source code

### Observed behavior
 
Current routing chain is long to reverse engineer

* `private-s3.internal.paas`is a bosh dns alias in dns-recursor to the `192.168.116.19` ip address
```
micro-depls/dns-recursor/template/1-dns-aliases-minio-operators.yml:

- type: replace
  path: /instance_groups/name=dns-recursor/jobs/name=bosh-dns/properties/aliases/private-s3.internal.paas?
  value: [192.168.116.19]
```

* `192.168.116.19` ip address is a VIP declared by metalb

```
master-depls/intranet-interco-relay/template/1-ops-relay-internal-vars.yml:

internal_ops_http_ip: 192.168.116.19  #--- metallb vip  
```

* TCP routing routes to the target k8s cluster 

```
micro-depls/00-core-connectivity-k8s/template/zz-external-route-minio-http-operators.yml:10

- type: replace
  path: /addons/name=10-add-servers/jobs/name=action/properties/actions/-
  value:
    type: kubectl
    name: "traefikingressrouteminio"
    cmd: "apply"
    options: ""
    content:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRouteTCP
      metadata:
        name: routingmapminio
        namespace: traefik
        annotations:
          kubernetes.io/ingress.class: traefik
      spec:
        entryPoints:
        - minio
        routes:
        - match: HostSNI(`*`)
          kind: Rule
          priority: 10
          services:
          - name: ci-k8s
            namespace: traefik
            kind: Service
            port: 32020
```            

* Target cluster has  nodeport sending to the minio pods

micro-depls/k8s-minio/template/3-minio-operators.yml:43

```
   values_file_content:
      service:
        type: NodePort
        clusterIP: ~
        port: 9000
        nodePort: 32020
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/minio/prometheus/metrics'
          prometheus.io/port: '9000'
```

### Possible improvements

Leverage labels on production system to be able to query routing elements related to a user/machine facing endpoint:
* add k8s label/annotation "paas-templates-relates-to-route: private-s3.internal.paas" on the K8S elements
* investigate if open-tracing could cross TCP routing barriers
* network traffic discovery tool ?

Ease source code correlation/reverse-engineering while keeping paas-templates author maintenance low 

### Affected releases

* 52.0.2
* earlier versions
