### ISSUE TITLE
feature-clean-ocb-services is incomplete and breaks COA consistency check

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1308]
### Expected behavior

* As a paas-templates operator 
* In order to deploy v52.0.2
* I need the `update-pipeline-micro-depls` to be successfull

#### ops-depls-update-generated/jobs/update-pipeline-ops-depls fails 

```
/tmp/build/fa403e5a/result-dir/lib/deployment_deployers_config.rb:29:in `load_configs': Inconsistency detected: deployment <cf-rabbit37> is marked as active, but no deployment-dependencies.yml, nor other deployer config directory found (concourse-pipeline-config, k8s-config) at ../templates/ops-depls/cf-rabbit37 (RuntimeError)
```

without automation of of clean up of `enable-deployment.yml`

upgrade/releases/v52.0.0/10-pre-upgrade/00-enforce-common-deployment-activations.rb will enable it automatically 

```
  def enable_ops_depls
    ops_deployments = %w[
      cf-rabbit37
      cf-rabbit-osb
      mongodb-osb
    ]
    ops_depls.enable_deployments(ops_deployments)
  end
```

#### grepping cf-rabbit37 show remaining uncleaned references

ops-depls/template/openstack-hws/vm-extensions-cf-rabbit37-cloud-operators.yml:4
```
- type: replace
  path: /vm_extensions?/-
  value:
    name: haproxy-cf-rabbit37-vrrp
    cloud_properties:
      #--- vrrp config ops-depls/cf-rabbit37/haproxy (see https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/pull/98)
      allowed_address_pairs: ((vrrp_ip_cf_rabbit37)) #--- #--- ip for port mapped to ops-depls/cf-rabbit37/haproxy
      #--- NOTE: port must be reserved in openstack by terraform rules (required by bosh cpi to retrieve port id from allowed ip)
```
master-depls/terraform-config/spec-openstack-hws/haproxy-cf-rabbit37-vrrp-ports.tf:1

### Affected releases

* 52.0.2
* earlier versions
