### ISSUE TITLE
Improve osbcmdb brokers cf health check

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1315]
### Expected behavior

* As a paas-templates operator 
* In order to 
   * ensure high availability of broker endpoints 
* I need
  * the brokers cf apps to be restarted by cloudfoundry when not healthy (not just process/or http port)
  

### Observed behavior

On prod environment, had osbcmdb broker frozen (http 500 responses to client. Cloudfoundry didnt detect unhealthy state.

v51 osbcmd cf apps manifest:

```
---
applications:
- name: osb-cmdb-broker-0
  env:
    logging.level.cloudfoundry-client: debug
...
    osbcmdb.maintenanceinfo.version: 1.1.0
    spring.cloud.appbroker.deployer.cloudfoundry.properties.health-check: http
    spring.cloud.appbroker.deployer.cloudfoundry.properties.health-check-http-endpoint: health
    spring.cloud.appbroker.deployer.cloudfoundry.properties.health-check-timeout: '180'
...
  buildpacks:
  - cached-java-buildpack
  stack: cflinuxfs3
  processes:
  - type: task
    instances: 0
    memory: 512M
    disk_quota: 512M
    health-check-type: process
  - type: web
    instances: 2
    memory: 1024M
    disk_quota: 512M
    health-check-type: port
    timeout: 180

```
 

### Affected releases

* x.y
* earlier versions
