### ISSUE TITLE
master-depls/osb-routing is polluting dns-recursors and iaas DNS servers with high rate incorrect DNS requests to 05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1319]
### Expected behavior

* As a paas-templates operator 
* In order to be able to troubleshoot DNS resolution errors
* I need DNS recursurs logs to not be polluted with DNS lookups for unknown paas-templates FQDNs

and 

* As a paas-templates operator 
* In order to make efficient usage of Iaas DNS resolvers
* I need only intranet/internet FQDN to be requested to Iaas DNS resolvers

### Observed behavior

DNS recursors are polluted  by high rate queries from master-depls/osb-routing 

```
dns-recursor/1b2c5038-6d56-432f-8172-657cefbbda17:/var/vcap/sys/log/bosh-dns# grep NXDOMAIN bosh_dns.stdout.log | grep 'from upstream' | grep ForwardHandler | awk '{print $12 }' | sort | uniq -c | sort -nr
  13964 05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats.
  [... others redacted]
```

The FQDN being unknown, the DNS requests are recursed to the iaas dns resolvers which return NXDOMAIN, and as a side effect trigger a recursor fail over (IP addresses were redacted)

```
[FailoverRecursor] 2021-10-01T07:46:02.931265751Z INFO - shifting recursor preference: a.b.c.d:53
[ForwardHandler] 2021-10-01T07:46:02.931618164Z DEBUG - error recursing to "a2.b.c.d:53": received NXDOMAIN for 05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats. from upstream (recursor: a2.b.c.d:53)
```

### Possible fixes

* osb-routing declares nats-release required bosh dns aliases

* dns resurcors are more selective in their forwarding of requests to iaas dns resolvers
   * white lists ?
   * black lists ? 
      * exclude paas-templates know internal TLDS

Not yet clear whether bosh dns would support such black lists, white lists can be handled through [handlers](https://github.com/cloudfoundry/bosh-dns-release/blob/2266a07a6df1a70157cbba6a9f0dc428fb800494/jobs/bosh-dns/spec#L78-L93)

### Diagnostic steps

After increase logs in bosh-dns agents on `osb-routing/nats` instance group, we get confirmation that DNS request are sent to bosh-dns of this vm

```
osb-routing-nats/05f62fc5-1384-485b-820e-665613ca0683:/var/vcap/sys/log/bosh-dns# less bosh_dns.stdout.log	
	
[CachingDNSHandler] 2021-10-05T15:56:33.050913562Z DEBUG - handlers.CachingDNSHandler Received request id=49677 qtype=[A] qname=[05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats.]
[ForwardHandler] 2021-10-05T15:56:33.050962315Z DEBUG - handlers.ForwardHandler Received request id=49677 qtype=[A] qname=[05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats.]
[CachingDNSHandler] 2021-10-05T15:56:33.051116187Z DEBUG - handlers.CachingDNSHandler Received request id=26240 qtype=[AAAA] qname=[05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats.]
[ForwardHandler] 2021-10-05T15:56:33.051149833Z DEBUG - handlers.ForwardHandler Received request id=26240 qtype=[AAAA] qname=[05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats.]
[ForwardHandler] 2021-10-05T15:56:33.053284416Z DEBUG - error recursing to "192.168.116.156:53": received NXDOMAIN for 05f62fc5-1384-485b-820e-665613ca0683.osb-routing-nats. from upstream (recursor: 192.168.116.156:53)
[FailoverRecursor] 2021-10-05T15:56:33.053292304Z INFO - shifting recursor preference: 192.168.116.166:53
```

This `osb-routing` FQDN is declared within paas-templates as `nats.hostname` property

https://github.com/cloudfoundry/nats-release/blob/5005adc9837684705b54862175de4e8cd0cfc5e5/jobs/nats/spec#L43-L45
>   nats.hostname:
>     description: "Hostname for nats cluster. Set this to the value of your bosh-dns-alias."
>     example: "nats.service.cf.internal"
> 

However the bosh dns alias is declare within the wrong bosh director

master-depls/osb-routing/template/osb-routing.yml
```
  properties:
    nats:
      password: "((nats_password))"
      user: nats
      hostname: osb-routing-nats #required from v34, should be bosh-dns alias of nats ?
``` 

The nats release indicate the requirement to declare two bosh dns aliases

https://github.com/cloudfoundry/nats-release/commit/fea7731dba3daf34bb6262a11bd1394492bd64c5

https://github.com/cloudfoundry/nats-release/commit/ff4b1d958c4ab8c19ae91b29cf422e987f4d8ed9
```
- type: replace
  path: /addons?/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=nats.service.cf.internal
  value:
    domain: nats.service.cf.internal
    targets:
    - deployment: cf
      domain: bosh
      instance_group: nats
      network: default
      query: '*'
``` 

This is usually vendored by the community using https://github.com/cloudfoundry/cf-deployment/blob/36288d27fb5c5ddf6d92115e7acf6397900a3e99/cf-deployment.yml#L327-L341
```
- name: bosh-dns-aliases
  jobs:
  - name: bosh-dns-aliases
    release: bosh-dns-aliases
    properties:
      aliases:
      - domain: nats.service.cf.internal
        targets:
        - query: '*'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
      - domain: _.nats.service.cf.internal
        targets:
        - query: '_'
          instance_group: nats
          deployment: cf
          network: default
          domain: bosh
```

### Affected releases

* x.y
* earlier versions
