### ISSUE TITLE
Concourse ui job outputs hang due to core-connectivity insufficient upstream-keepalive-timeout (default 60s)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1364]
### Expected behavior

* As a paas-templates operator 
* In order to operate the platform
* I need to use concourse to track completion of long running tasks (such as `bosh deploy`)

### Observed behavior
 
Concourse UI freezes on long running jobs, not updating job output or the pipeline job completion status

### Diagnostic and possible fix

In firefox developer module, we see the https://elpaaso-concourse.redacted-ops-domain.org/api/v1/builds/74004636/events query remains on hold. See background at https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_server-sent_events. They are server-service events

Reproducing in curl (through firefox option `copy as posix curl`) we see that the http request is terminated before the last event

Abnormal case with unexpected connection cloe
```
id: 236
event: event
data: {"data":{"time":1634714763,"origin":{"id":"61619e92","source":"stderr"},"payload":"\nTask 6254099 | 07:26:02 | Updating instance uaa-backend: uaa-backend/f1f276dc-c046-4a60-ac33-237fa6f99bd9 (0) (canary)"},"event":"log","version":"5.1","event_id":"236"}

curl: (18) transfer closed with outstanding read data remaining
```

Expected case were the last event `end` is properly received
```
id: 397
event: event
data: {"data":{"status":"succeeded","time":1634714074},"event":"status","version":"1.0","event_id":"397"}

id: 398
event: end
data

curl: (18) transfer closed with outstanding read data remaining
```

In the nginx daemon set logs, we eventually see an associated error trace
`    ingress-nginx-controller-fn9mf 2021/10/20 07:32:05 [error[] 227#227: *560250 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: elpaaso-concourse.redacted-ops-domain.org, request: "GET /api/v1/builds/74004636/events HTTP/1.1", upstream: "http://192.168.116.162:8080/api/v1/builds/74004636/events", host: "elpaaso-concourse.redacted-ops-domain.org"`

The correponding ingress-nginx at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#upstream-keepalive-timeout specifies the default keep
>     upstream-keepalive-timeout
> 	Sets a timeout during which an idle keepalive connection to an upstream server will stay open. default: 60
> References: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_timeout

http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive_timeout

> <html><body>
> <div class="directive">
> 
> Syntax: | keepalive_timeout timeout;
> -- | --
> keepalive_timeout 60s;
> upstream
> 
> <p>This directive appeared in version 1.15.3.
>             </p></div><p>
> Sets a timeout during which an idle keepalive
> connection to an upstream server will stay open.
> </p>
> </body>
> </html>
> 

The helm chart supports custom entry in the config map https://github.com/kubernetes/ingress-nginx/blob/8611ecb7c97ce286e2e171a7e6e6aa50d2398b0c/charts/ingress-nginx/values.yaml#L36-L37

>     # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
>     config: {}

### Workaround

* Reload the page within the browser
* Manually patch the configmap `ingress-nginx-controller` in namespace `ingress-nginx` in coreconnectivity k8s cluster

```yaml
upstream-keepalive-timeout: 300
```

### Affected releases

* 52.0.3
* earlier versions

**Comment by gberche-orange** [comment]
Test with `upstream-keepalive-timeout: "1200" # fix for #1364` in paas-templates/micro-depls/k8s-jcr/template/02-ingress-nginx-helm-operators.yml did not solve the problem, still observing nginx-controller timeout traces.

**Comment by gberche-orange** [comment]
Still observing nginx ingress timeout with concourse 7.6.0 and a trace similar to 

```
ingress-nginx-controller-fn9mf 2021/10/20 07:32:05 [error[] 227#227: *560250 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: elpaaso-concourse.redacted-ops-domain.org, request: "GET /api/v1/builds/74004636/events HTTP/1.1", upstream: "http://192.168.116.162:8080/api/v1/builds/74004636/events", host: "elpaaso-concourse.redacted-ops-domain.org"
```

v52 config from nginx ingress to concourse IP addresses
```yaml
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: concourse-ingress
        namespace: ingress-nginx
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
      spec:
        rules:
        - host: elpaaso-concourse.((/secrets/cloudfoundry_ops_domain))
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: concourse-route
                  port:
                    number: 8080
        tls:
        - hosts:
          - elpaaso-concourse.((/secrets/cloudfoundry_ops_domain))
          secretName: concourse-ssl
```


```yaml
      apiVersion: v1
      kind: Service
      metadata:
        name: concourse-route
        namespace: ingress-nginx #to be accessible from nginx-ingress
      spec:
        externalName: q-s0.web.net-bosh-2.concourse.bosh
        type: ExternalName
```
