### ISSUE TITLE
Coab is not exposing OSB context mutable names such as cmdb org name (i.e. only immutable guids)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1395]
### Expected behavior

* As a paas-templates operator
* In order to get the cmdb client platform name in bosh deployments, including prometheus metrics or vm tag 
* I need coab to propagate the [osb cloudfoundry profile](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md) in particular:
   * context.organization_name: useful to identify the osb-cmdb backing org which is the osb consummer platform

### Observed behavior
 
Initial design decision to only expose immutable data in coab-vars.yml context

```
deployment_name: "y_1402230d-481e-42a8-8eba-ad5325831b93"
instance_id: "1402230d-481e-42a8-8eba-ad5358879b49"
service_id: "cf-mysql-ondemand-service"
plan_id: "plan-coab-mariadb-small"
context:
  platform: "cloudfoundry"
  user_guid: "c99c44f8-6342-43bc-948d-2ae495338013"
  space_guid: "762a66e6-6d34-476e-82b2-03fae16cc225"
  organization_guid: "87ae7493-654d-43ea-bf07-931e49cf68cc"
```

### Affected releases

* 52.0.5
* earlier versions

**Comment by gberche-orange** [comment]
Mitigated by the fact that osb-cmdb provides the org name in `x-osb-cmdb.annotations.brokered_service_client_name`

in coab-vars.yml

```yaml
---
deployment_name: "y_..."
instance_id: "..."
service_id: "cf-mysql-ondemand-service"
plan_id: "plan-coab-mariadb-medium"
context:
  platform: "cloudfoundry"
  user_guid: "..."
  space_guid: "..."
  organization_guid: "..."
parameters:
  x-osb-cmdb:
    annotations:
      brokered_service_client_name: "cmdb-cf-z1-services"
```
