### ISSUE TITLE
Ease traceability/inspections of helm chart sources

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1418]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to troubleshoot/inspect a helm chart
* I need to get access to its public git sources 

### Observed behavior
 
The git source urls are documented within feature bump branches, e.g.     https://github.com/orange-cloudfoundry/paas-templates-private/pull/953
> bump nginx helm chart - https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.0.6

* For bosh-based helm releases, the `shared-operators/k8s-common/helm-charts-versions-vars.yml` file lists the source url
* For flux-based helm release, the helm chart version is specified in shared-operators/k8s-kustomize-bases/helm/nginx-ingress/nginx-ingress-helm-release.yaml but does not indicate the source url

Also the flux source controller can be inspected in ssh to double check the actual helm chart sources. Open a shell into pod flux-system/source-controller-xx

```
controller@source-controller-d454b4986-wvpjk:/$ find ./data/
./data/
./data/helmchart
./data/helmchart/fluxcd
./data/helmchart/fluxcd/traefik-ingress-nginx
./data/helmchart/fluxcd/traefik-ingress-nginx/traefik-9.19.1.tgz.lock
./data/helmchart/fluxcd/traefik-ingress-nginx/traefik-latest.tgz
./data/helmchart/fluxcd/traefik-ingress-nginx/traefik-9.19.1.tgz
./data/helmchart/fluxcd/ingress-nginx-ingress-nginx
./data/helmchart/fluxcd/ingress-nginx-ingress-nginx/ingress-nginx-4.0.6.tgz.lock
./data/helmchart/fluxcd/ingress-nginx-ingress-nginx/ingress-nginx-4.0.6.tgz
./data/helmchart/fluxcd/ingress-nginx-ingress-nginx/ingress-nginx-latest.tgz
./data/helmchart/fluxcd/intranet-smtp-proxy-smtp-haproxy
./data/helmchart/fluxcd/intranet-smtp-proxy-smtp-haproxy/haproxy-latest.tgz
./data/helmchart/fluxcd/intranet-smtp-proxy-smtp-haproxy/haproxy-0.1.1.tgz.lock
./data/helmchart/fluxcd/intranet-smtp-proxy-smtp-haproxy/haproxy-0.1.1.tgz
./data/helmchart/fluxcd/harbor-harbor
./data/helmchart/fluxcd/harbor-harbor/harbor-10.0.2.tgz.lock
./data/helmchart/fluxcd/harbor-harbor/harbor-10.0.2.tgz
./data/helmchart/fluxcd/harbor-harbor/harbor-latest.tgz
./data/helmchart/fluxcd/traefik-traefik
./data/helmchart/fluxcd/traefik-traefik/traefik-9.19.1.tgz.lock
./data/helmchart/fluxcd/traefik-traefik/traefik-latest.tgz
./data/helmchart/fluxcd/traefik-traefik/traefik-9.19.1.tgz
./data/helmchart/jcr
./data/helmchart/jcr/jcr-artifactory-jcr
./data/helmchart/jcr/jcr-artifactory-jcr/artifactory-jcr-3.4.1.tgz.lock
./data/helmchart/jcr/jcr-artifactory-jcr/artifactory-jcr-3.4.1.tgz
./data/helmchart/jcr/jcr-artifactory-jcr/artifactory-jcr-latest.tgz
./data/gitrepository
./data/gitrepository/fluxcd
./data/gitrepository/fluxcd/gitops-depls
./data/gitrepository/fluxcd/gitops-depls/97ea56eccab332fc84915a16bbd24fa8534c0f97.tar.gz
./data/gitrepository/fluxcd/gitops-depls/latest.tar.gz
./data/gitrepository/fluxcd/paas-k8s-gitops-repo
./data/gitrepository/fluxcd/paas-k8s-gitops-repo/97ea56eccab332fc84915a16bbd24fa8534c0f97.tar.gz
./data/gitrepository/fluxcd/paas-k8s-gitops-repo/latest.tar.gz
./data/helmrepository
./data/helmrepository/fluxcd
./data/helmrepository/fluxcd/helm-repo
./data/helmrepository/fluxcd/helm-repo/index.yaml
./data/helmrepository/fluxcd/helm-repo/index-035aead0041a3f3fed8259b674a205a5d33a4584cdb01275aefb62065e6a8d21.yaml
./data/helmrepository/jcr
./data/helmrepository/jcr/jfrog
./data/helmrepository/jcr/jfrog/index.yaml
./data/helmrepository/jcr/jfrog/index-36832602c4766fd80f625c6e4868d439f9b1954d4cee830399700d144e845c20.yaml
```

### Possible fix

Add the source url as an annotation each flux HelmRelease object 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  annotations:
      paas-templates-helm-source-url: "https://github.com/kubernetes/ingress-nginx/releases/tag/helm-chart-4.0.6" 
spec:
  interval: 3m
  chart:
    spec:
      chart: ingress-nginx
      version: "3.30.0" #helm_ingress_nginx
      sourceRef:
        kind: HelmRepository
        name: helm-repo
        namespace: fluxcd
      interval: 5m
```      

### Affected releases

* 52.x
* earlier versions
