### ISSUE TITLE
Flux helm debug traces 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1430]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to troubleshoot slow helm reconciliation which take much time on the wait for jobs
* I need flux helm controller debug traces

### Observed behavior
 
Flux helm controller has info traces with default installation: paas-templates/shared-operators/k3s/fluxcd/50-install-fluxcd-operators.yml

```
- type: replace
  path: /addons/name=10-add-servers/jobs/name=action/properties/actions/-
  value:
    type: kubectl
    name: "fluxcd-apply-install"
    namespace: flux-system
    cmd: "apply"
    options: "-f https://github.com/fluxcd/flux2/releases/download/v0.23.0/install.yaml"
```    

### Affected releases

* 52.x
* earlier versions
