### ISSUE TITLE
bosh hm proxy : "agent is not a part of any deployment"

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1446]
### Expected behavior

* As a paas-templates operator
* In order to 
* I need 

### Observed behavior
on v53.0.0, openstack iaas-type, receiving the following mail notification.

```
agent 940c39ed-2371-4a01-a1df-7a56a67f2abb []
940c39ed-2371-4a01-a1df-7a56a67f2abb is not a part of any deployment
```

```
hm
Health monitor failed to connect to director
Severity: 3
Summary: Cannot get status from director at https://127.0.0.1:25555/info: 0 
Time: 2022-01-05 19:39:57 UTC

```

/var/vcap/sys/log/health_monitor
```
```
```
bosh/df0a66e8-3598-47ec-931f-8c60c1efba09:/var/vcap/jobs/health_monitor/config# pwd
/var/vcap/jobs/health_monitor/config
bosh/df0a66e8-3598-47ec-931f-8c60c1efba09:/var/vcap/jobs/health_monitor/config# cat bpm.yml 
---
processes:
- name: health_monitor
  executable: "/var/vcap/jobs/health_monitor/bin/health_monitor"
  env:
    BUNDLE_GEMFILE: "/var/vcap/packages/health_monitor/Gemfile"
    GEM_HOME: "/var/vcap/packages/health_monitor/gem_home/ruby/3.0.0"
    HTTP_PROXY: http://system-internet-http-proxy.internal.paas:3128
    http_proxy: http://system-internet-http-proxy.internal.paas:3128
    HTTPS_PROXY: http://system-internet-http-proxy.internal.paas:3128
    https_proxy: http://system-internet-http-proxy.internal.paas:3128
    NO_PROXY: 127.0.0.1,localhost,169.254.0.0/16,192.168.0.0/16,.internal.paas,.xxx
    no_proxy: 127.0.0.1,localhost,169.254.0.0/16,192.168.0.0/16,.internal.paas,.xxxx
  unsafe:
    unrestricted_volumes:
    - path: "/var/vcap/jobs"
    - path: "/var/vcap/data/jobs/*/*/bin/bosh-monitor"
      allow_executions: true
    - path: "/var/vcap/sys/log"
      writable: true
      mount_only: true

```

### references
- https://github.com/orange-cloudfoundry/paas-templates/issues/1445
- https://github.com/cloudfoundry/bosh/issues/2331
  - no_proxy regression introduced in bosh 217.9.0 (v52 uses 217.8.0)
  - fix is merged, waiting for 217.18 release cut

### Affected releases

* pre 53.0.0, bosh 271.17.0
