### ISSUE TITLE
Last rendered kustomizations are not deterministic, triggering extra commits/reconciliations

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1563]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to contribute/monitor
* I need no noise in gitops repo history
* I need Kustomization reconciliations to only trigger on real changes

### Observed behavior
 
00-bridge-kustomizations have changes related so to 
![image](https://user-images.githubusercontent.com/4748380/161005603-1e2389a9-cd8a-4fe7-b86e-a714e8225c8c.png)

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: credhub-secrets
  files:
  [...]
  - plan_prices_plan_shared_mariadb_100mb_price=plan_prices_plan_shared_mariadb_100mb_price.value
  - plan_prices_plan_shared_mariadb_10mb_price=plan_prices_plan_shared_mariadb_10mb_price.value
  - plan_prices_plan_shared_mariadb_15gb_price=plan_prices_plan_shared_mariadb_15gb_price.value
  - plan_prices_plan_shared_mariadb_1gb_price=plan_prices_plan_shared_mariadb_1gb_price.value
  - plan_prices_plan_shared_mariadb_20mb_price=plan_prices_plan_shared_mariadb_20mb_price.value
```

Suspecting the 

### References

Likely related to kustomize build output key sorting https://github.com/kubernetes-sigs/kustomize/issues/4292

### Alternatives

* remove Kustomize file rendering
* specific case for `plan_prices_plan_shared_mariadb` 
   * exclude credhub key from config map generation
   * exclude unused variable `plan_prices_plan_shared_mariadb` from last rendered kustomization: 
   * exclude 00-bridge-kustomizations from rendered kustomizations
* yaml pretty formatting

### Affected releases

* x.y
* earlier versions
