### ISSUE TITLE
bosh deployment recovery not possible with pre-compile information inside the manifest 

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1607]
### Expected behavior
* As a paas-templates operator
* In order to have a clean bosh deployment state before upgrading my platform
* I need a procedure to recover my bosh deployment 

### Observed behavior
Following a bad manipulation on the IAAS  (manual DRS mode) when upgrading bosh deployments, some VMs have been deleted and are now missing.
It is not possible to recover with bosh cck or bosh deploy commands (on bosh-coab/cf-mysql-r1z2), the message is : 
```
Can't use release 'cf-mysql/38.0.0':
Packages must be exported from stemcell 'ubuntu-bionic/1.34', but some packages are not compiled for this stemcell:
```

### Workaround applied
- bosh -d <my_deployment> manifest > manifest.yml
- edit the file manifest.yml (look for "releases" tag) and replace : 
```
releases:
- exported_from:
  - os: ubuntu-bionic
    version: "1.34"
  name: cf-mysql
  sha1: ""
  stemcell:
    os: ubuntu-bionic
    version: "1.34"
  url: http://private-s3.internal.paas:9000/compiled-releases/orange-cloudfoundry/cf-mysql-38.0.0-ubuntu-bionic-1.34.tgz
  version: 38.0.0
```
by
```
releases:
- name: cf-mysql
  version: 38.0.0
```

### Affected releases
v53.0.4
