### ISSUE TITLE
kyverno policy referenced inside kustomization not applied if the fluxcd kustomization contains an empty line

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/paas-templates#1627]
### Expected behavior
* As a paas-templates paas-templates author
* In order to customize my workloads (additional container, proxy usage, ca-cert addition)
* I need kyverno policy applied

### Observed behavior
Given the following fluxcd kustomization entry point with an empty line : 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 10-prometheus-sandbox

spec:
  #post-build substitution
  postBuild:
    substitute:
      clientID: "supervision-client"
      clientSecret: "((/uaa/supervision-client-secret))"
      cookieSecret: "((/uaa/supervision-cookie-secret))"
```

Given the following kustomization file : 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 10-prometheus-sandbox
resources:
  - ../../../../../shared-operators/k8s-kustomize-bases/observability
  - ../../../../../shared-operators/k8s-kustomize-bases/helm/oauth2-proxy
  - additional-scrape-config-secret.yaml
  - generate-tls-configmap.yaml
```

kyverno policies located in ../../../../../shared-operators/k8s-kustomize-bases/observability are not applied

### Traces 
```
kyverno E0617 15:16:39.066037       1 configmanager.go:152] WebhookConfigManager "msg"="failed to sync policy" "error"="failed to update policy status 10-prometheus-sandbox/kyverno-discovery-file-side │
│ -car: Operation cannot be fulfilled on policies.kyverno.io \"kyverno-discovery-file-side-car\": the object has been modified; please apply your changes to the latest version and try again"  "key"="10- │
│ prometheus-sandbox/kyverno-discovery-file-side-car"                                                                                                                                                      │
```
 
### Solution
Remove empty line in fluxcd Kustomization entry point as below : 
```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 10-prometheus-sandbox
spec:
  #post-build substitution
  postBuild:
    substitute:
      clientID: "supervision-client"
      clientSecret: "((/uaa/supervision-client-secret))"
      cookieSecret: "((/uaa/supervision-cookie-secret))"
```
