### ISSUE TITLE
bosh director nginx is configured properly

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#1704]
### Expected behavior

* As a paas-templates operator
* In order to ease bosh director debugging
* I need have a valid config for nginx

#### fix error.log path
Currently, `/var/vcap/sys/log/director/nginx.stderr.log` is a duplicate of `/var/vcap/sys/log/director/error.log`

```
nginx: [alert] could not open error log file: open() "/var/vcap/packages/nginx/logs/error.log" failed (30: Read-only file system)
``` 

Extract of nginx.conf (cat /var/vcap/data/jobs/director/*/config/nginx.conf)
```
error_log /var/vcap/sys/log/director/error.log;
pid       /var/vcap/data/director/nginx.pid;

events {
  worker_connections 8192;
}
```

So we should not have errors about read-only FS.

#### Increase ulimit

After increasing log level, from error to `warn`, message below is displayed:
```
nginx: [warn] 8192 worker_connections exceed open file resource limit: 1024
```
We can use bpm, to increase ulimlit, update `bpm.yml`, in bosh, accordingly:
```yaml
- name: nginx
  executable: "/var/vcap/packages/nginx/sbin/nginx"
  args:
  - "-c"
  - "/var/vcap/jobs/director/config/nginx.conf"
  ephemeral_disk: true
  limits:
    open_files: 65536
```

### Affected releases

* 54.0.2
