### ISSUE TITLE
VM-level tag to support graceful degradation in face of power restrictions

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1725]
### Expected behavior

* As a paas-templates operator
* I need to maximize business value (uptime for most valuable customers workloads) within restricted available power
* I need to tag vms with
   * Business related traceability: is_prod, corporate_app_code (available from 
   * Priority for business continuity

### Observed behavior

* heavy usage of vm tags on openstack were observed to high openstack api rate limit: https://github.com/orange-cloudfoundry/paas-templates/issues/1435
* COAB bosh deployments only include the following vm tags

```
tags:
  coa-templates-commit-author: redacted@me.com
  coa-templates-commit-id: df42[... ]
  paas_templates_version: 53.0.4
```
  
*Coab bosh deployment manifest contain

```yaml
coab_completion_marker:
  context:
    organization_guid: ...
    platform: cloudfoundry
    space_guid:  ...
    user_guid:  ...
  deployment_name: z-db3e24dc-dd53-41df-be23-d833e792616f
  instance_id: db3e24dc-dd53-41df-be23-d833e792616f
  parameters:
    x-osb-cmdb:
      annotations:
        brokered_service_api_info_location: fake-endpoint/v2/info
        brokered_service_context_instanceName: strimzi-smoketest-1657779578
        brokered_service_context_organizationName: service-sandbox
        brokered_service_context_spaceName: coa-strimzi-smoke-tests
      labels:
        brokered_service_context_organization_guid: a-faked-org-guid-in-coab-smoke-tests
        brokered_service_context_space_guid: a-faked-space-guid-in-coab-smoke-tests
        brokered_service_instance_guid: strimzi-smoketest-1657779578
        brokered_service_originating_identity_user_id: a-faked-user-guid-in-coab-smoke-tests
  plan_id: plan-coab-strimzi-small
  service_id: strimzi-ondemand-service
```

### Affected releases

* x.y
* earlier versions
