### ISSUE TITLE
GCP-depls kyverno bootstrap install is lacking production-ready adjustments

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1879]
### Expected behavior

* As a paas-templates operator 
* In order to avoid kyverno negatively impact the platform
* I need kyverno sizing to the production ready https://github.com/kyverno/kyverno/tree/main/charts/kyverno#high-availability
> Running a highly-available Kyverno installation is crucial in a production environment.
> 
> In order to run Kyverno in high availability mode, you should set replicaCount to 3 or more. You should also pay attention to anti affinity rules, spreading pods across nodes and availability zones.
> 
> Please see https://kyverno.io/docs/installation/#security-vs-operability for more informations.
> 
> 

### Observed behavior
 
* [ ] tunings from `micro-depls/00-core-connectivity-k8s/template/21-install-kyverno-operators.yml` are missing

```yaml
- type: replace
  path: /addons/name=10-add-servers/jobs/name=action/properties/actions/-
  value:
    type: helm_chart
    name: kyverno
    chart: kyverno/kyverno
    namespace: kyverno
    version: ((helm_kyverno))
    values_file_content:
      replicaCount: 3 #for ha

```

* [ ]  memory tuning w.r.t. high number of CRDs loaded for crossplane
* [ ]  namespace exclusions
* [ ]  anti affinity rules, spreading pods across nodes and availability zones
* [ ] locating kyverno pods on openshift master/infra nodes 

### References

* https://kyverno.io/support/redhat/
* https://github.com/orange-cloudfoundry/paas-templates/issues/1815
> 
> Also helm release notes displays
> 
> Chart version: 2.6.4-rc.1
> Kyverno version: v1.8.4-rc.1
> 
> Thank you for installing kyverno! Your release is named kyverno.
> ⚠️  WARNING: Setting replicas count below 3 means Kyverno is not running in high availability mode.
> 
> 💡 Note: There is a trade-off when deciding which approach to take regarding Namespace exclusions. Please see the documentatio

* https://docs.openshift.com/container-platform/4.12/nodes/nodes/nodes-nodes-creating-infrastructure-nodes.html
> You can use infrastructure machine sets to create machines that host only infrastructure components, such as the default router, the integrated container image registry, and the components for cluster metrics and monitoring. These infrastructure machines are not counted toward the total number of subscriptions that are required to run the environment.

* https://docs.openshift.com/container-platform/4.12/nodes/index.html
> Overview of nodes
> A node is a virtual or bare-metal machine in a Kubernetes cluster. Worker nodes host your application containers, grouped as pods. The control plane nodes run services that are required to control the Kubernetes cluster.
> 

### Affected releases

* x.y
* earlier versions
