### ISSUE TITLE
argoworkflow ingress fails due to certificat secret mismatch

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1893]
### Expected behavior

* As a paas-templates operator 
* In order to use argoworkflow to run osb-smoke tests
* I need a valid intranet-facing HTTP route

### Observed behavior
 
![image](https://user-images.githubusercontent.com/4748380/221827241-86745bdc-512f-42c2-a3b8-9d7e7cace3e5.png)

The certificate is not trusted because it is self-signed.
 
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

https://support.mozilla.org/en-US/kb/error-codes-secure-websites#w_self-signed-certificate

### Diagnostic

```
$ k ns 01-loadbalancer
$ k logs ds/ingress-nginx-controller

W0228 09:58:14.773209       7 controller.go:1333] Error getting SSL certificate "20-argo/tls": 
local SSL certificate 20-argo/tls was not found. Using default certificate
```

Check tls secret, see https://blog.kubovy.eu/2020/05/16/retrieve-tls-certificates-from-kubernetes/

```
$ k get -n 20-argo secret/tls -o json | jq -r '.data."tls.crt"' | base64 -d | base64 -d | openssl x509 -noout -text | grep -i "CN = "
[...]
```
There is a domain mismatch between the url https://argo-workflows-marketplace.<ops-domain>/ and the certficate: 

paas-templates/master-depls/00-marketplace/k8s-config/manifests/20-argo/argo-workflow-helm-release-patch.yaml
```yaml
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
        - argo-workflows-marketplace.${cloudfoundry_ops_domain}
        tls:
        - secretName: tls
          hosts:
          - argo-workflows-marketplace.${cloudfoundry_ops_domain}
```

```
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: kubernetes.io/tls
stringData:
  tls.crt: ${certs_dnsaas_certificate} # certFilename
  tls.key: ${certs_dnsaas_private_key} # certKeyFilename
```

### Affected releases

* x.y
* earlier versions
