### ISSUE TITLE
HelmRelease - source not ready, x509 cert issue in sourcemanager

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#1907]
### Expected behavior

* As a paas-templates operator | paas-templates author 
* In order to deploy helm charts
* I need the HelmRelease to synchronize

### Observed behavior

Version:
- flux 0.39 and other
- k8s 1.24
- jcr  artifactory-jcr-107.41.14  / 7.41.14  


HelmRelease state
```
vents:                                                                                                                                             

  Type    Reason  Age                    From             Message                                                                                   
  ----    ------  ----                   ----             -------                                                                                   
  Normal  info    8m56s (x242 over 40h)  helm-controller  HelmChart 'fluxcd/10-prometheus-kube-prometheus-stack' is not ready                       
``` 


Flux source controller logs:

```
/data/helmrepository/fluxcd/helm-repo $ ls
index-d35ab4d6456bcb0cbeae13c55df24505e97ee562ab4bf406d23705c6c902f7a5.yaml
index-d35ab4d6456bcb0cbeae13c55df24505e97ee562ab4bf406d23705c6c902f7a5.yaml.lock
index.yaml


{"level":"error","ts":"2023-03-13T08:58:11.095Z","msg":"Reconciler error","controller":"helmchart","controllerGroup":"source.toolkit.fluxcd.io","con
trollerKind":"HelmChart","HelmChart":{"name":"10-prometheus-kube-prometheus-stack","namespace":"fluxcd"},"namespace":"fluxcd","name":"10-prometheus-
kube-prometheus-stack","reconcileID":"23562418-a356-4175-b97e-ccfde502b0dd","error":"chart pull error: failed to download chart for remote reference
: Get \"https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-36.2.0/kube-prometheus-stack-36.2.0.tgz\": x509:
 certificate is valid for github.com, www.github.com, not jcr-k8s.<redacted ops domain>"}                                                 

```

Examine fluxcd source controller cached index.yaml (located in the pod )

```
  - apiVersion: v2                                                          
    created: 2023-03-08T16:08:44.930559601Z                                 
    description: "kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scri
    digest: 2305abac8f6fd59455f982a02c21a9e1e8ca44804820c101b85f3c2571eae548                                                                        
    home: https://github.com/prometheus-operator/kube-prometheus                                                                                    
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png                           
    name: kube-prometheus-stack            
    sources:                               
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus                                              
    urls:                                                   
    - https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-45.7.0/kube-prometheus-stack-45.7.0.tgz           

```

Seems the url is not rewritten to paas-templates jcr-k8s.<ops_domain>.


### Analysis

as of v55, prometheus HelmRepository is ok, wired to the internet repo (not leveraging jcr)
Seems the jcr helm virtual repo is broken, no url rewrite ?

Following an initial application of the kyverno policy, the corporate ca cert is injected as `certRef`. Excluding the HelmRelease from the policy does not rollback this change (#1529)

### Workaround

Following an exclude of a HelmRepository from the kyverno policy, delete the HelmRepository and the HelmRelease to get it recreated by flux.

```yaml
kind: HelmRepository                                                                                                                                                                                               
metadata:                                                                                                                                                                                                          
  annotations:                                                                                                                                                                                                     
    paas-templates.kustomize.toolkit.fluxcd.io/do-not-use-harbor-cache: "true"   
```
### References
- https://github.com/fluxcd/flux2/issues/2019
> Just one thing that confuses me a little is that the URL is clearly https://github.com/... but the error says the cert isn't valid for airflow-helm.github.io. 🤔
 
### Affected releases

* 56
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
