### ISSUE TITLE
Collect and alert on vmware vsphere alarms

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#1950]
### Expected behavior

* As a paas-templates operator 
* In order to be alerted when vsphere-level alarms triggers
* I need the vmware exporter to be configured to fetch vsphere alarms

### Observed behavior

By defaults alarms are not fetched 
 
https://github.com/pryorda/vmware_exporter 

<html><body>
<h4 tabindex="-1" dir="auto"><a id="user-content-environment-variables" class="anchor" aria-label="Heading link" href="https://github.com/pryorda/vmware_exporter#environment-variables"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a>Environment Variables</h4>

Variable | Precedence | Defaults | Description
-- | -- | -- | --
VSPHERE_FETCH_ALARMS | config, env | False | Fetch objects triggered alarms, and in case of hosts hdw alarms as well

</body>
</html>

master-depls/bosh-remote-r2/template/80-r2-vsphere/6-iaas-exporter-vsphere-operators.yml

```yaml
#--- Add vsphere exporter as a docker container
- type: replace
  path: /instance_groups/name=bosh/jobs/name=containers/properties/containers/-
  value:
    name: vsphere_iaas_exporter
    image: pryorda/vmware_exporter:((pryorda/vmware_exporter))
    bind_ports:
    - "9272:9272"
    env_vars:
    - "VSPHERE_USER=((/secrets/vsphere_2_vcenter_user))"
    - "VSPHERE_PASSWORD=((/secrets/vsphere_2_vcenter_password))"
    - "VSPHERE_HOST=((/secrets/vsphere_2_vcenter_ip))"
    - "VSPHERE_IGNORE_SSL=True"
    - "VSPHERE_SPECS_SIZE=2000"
    - "VSPHERE_FETCH_CUSTOM_ATTRIBUTES=True"
    - "VSPHERE_FETCH_TAGS=True"
    - "https_proxy=http://intranet-http-proxy.internal.paas:3129"
    - "http_proxy=http://intranet-http-proxy.internal.paas:3129"
```    

### Affected releases

* 55.x
* earlier versions
