### ISSUE TITLE
bridge kyverno Policy leaks

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2019]
### Expected behavior

* As a paas-templates operator
* In order to 
  * install v55 successfully 
* I need 
  * the gitops mechanism to apply v55 Kyverno Policies AND remove v54 old bridge Policies
   

### Observed behavior
 
v55 policies are applied successfully
but v54 policy are still present, giving conflicts (missing excludes)

provisionned policies
```
$ kubectl get Policy -A
NAMESPACE                           NAME                                             BACKGROUND   VALIDATE ACTION   READY
cattle-system                       kyverno-add-ca-cert                              false        audit             true
flux-system                         kyverno-fluxcd-add-ca-cert-deployments           false        audit             true
flux-system                         kyverno-fluxcd-helmcontroller-log-level          false        audit             true
fluxcd                              root-kustomizations-substitute-policy            false        audit             true
flux-system                         kyverno-fluxcd-add-notification-intranet-proxy   false        audit             true
fluxcd                              fluxcd-root-kustomizations-policy                false        audit             true
55-dedicated-bosh-vms-dns-records   configure-external-dns-commons                   false        audit             true
10-prometheus                       thanos-sidecar-bucket-access-policy              false        audit             true
fluxcd                              root-kustomizations-policy                       false        audit             true

```

See kustomization inventory

```
  prune: false
status:
  conditions:
  - lastTransitionTime: "2023-07-04T15:42:34Z"
    message: 'Applied revision: master/bf783878c12bcdccad2591e0762d2067a644a16a'
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  inventory:
    entries:
    - id: fluxcd_coa-metadata__ConfigMap
      v: v1
    - id: fluxcd_credhub-secrets__ConfigMap
      v: v1
    - id: fluxcd_paas-k8s-gitops-kustomization_kustomize.toolkit.fluxcd.io_Kustomization
      v: v1beta2
    - id: fluxcd_paas-k8s-gitops-kustomization-iaas_kustomize.toolkit.fluxcd.io_Kustomization
      v: v1beta2
    - id: fluxcd_paas-k8s-gitops-kustomization-profiles_kustomize.toolkit.fluxcd.io_Kustomization
      v: v1beta2
    - id: _block-protected-deletion_kyverno.io_ClusterPolicy
      v: v1
    - id: fluxcd_fluxcd-root-kustomizations-policy_kyverno.io_Policy
      v: v1
```

### workaround
manually remove Kyverno Policies

##

### Affected releases

* 55.0.3
* earlier versions
