### ISSUE TITLE
Recovery procedure for failed bosh deploy of 00-core-connectivity-k8s

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2061]
### Expected behavior

* As a paas-templates operator
* In order to cope with a failed `bosh deploy` of `00-core-connectivity-k8s` where ingress traffic isn't routed, preventing access to gitlab, concourse, harbor, minio etc
* I need a recovery procedure

### Observed behavior
 
Need a way to recover the attempted bosh deployment manifest

### Workaround

The following procedure provides a way to recover the bosh manifest previously requested by concourse which is not available to operators (since concourse is unreacheable, and the manifest may not have been pushed to gitlab, and gitlab is unreacheable)

* Identity the bosh task id (e.g. `14994867`) where the failing bosh deploy occured
* `bosh task --debug 14994867 > 14994867.yaml`
* vi the `14994867.yaml` to remove the header and truncate file at the end of the manifest (with vi `dG` sequence, see https://stackoverflow.com/questions/8124315/how-i-can-delete-in-vim-all-text-from-current-line-to-end-of-file)

```
, [2023-09-05T16:37:28.216456 #65814] [task:14994867]  INFO -- DirectorJobRunner: Reading deployment manifest
D, [2023-09-05T16:37:28.230042 #65814] [task:14994867] DEBUG -- DirectorJobRunner: Manifest:

addons:
addons:
- exclude:
    jobs: []
  include:
    jobs:
[...]
 name: jcr_admin_password
  type: password

', "has_stale_errand_links" = false, "links_serial_id" = 235 WHERE ("id" = 191)
D, [2023-09-05T16:37:28.290017 #65814] [task:14994867] DEBUG -- DirectorJobRunner: (0.003625s) (conn: 7280) COMMIT
I, [2023-09-05T16:37:28.290494 #65814] [task:14994867]  INFO -- DirectorJobRunner: sending update deployment start event
```
* possibly edit some release that would be attempted to be downloaded
from
```yaml
- name: helm-kubectl
  sha1: ""
  stemcell:
    os: ubuntu-jammy
    version: "1.207"
  url: http://private-s3.internal.paas:9000/compiled-releases/orange-cloudfoundry/helm-kubectl-40-ubuntu-jammy-1.207.tgz
  version: "40"
```

to 

```yaml
- name: helm-kubectl
  version: "40"
```
* `bosh deploy --fix 14994867.yaml`

### Affected releases

* x.y
* earlier versions
