### ISSUE TITLE
56.0.0 rc0 00-core-connectivity-k8s vms are lacking node_exporter

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2091]
### Expected behavior

* As a paas-templates operator 
* In order to observe vms in 00-core-connectivity-k8s
* I need the node_exporter to be deployed

### Observed behavior

All vms in 00-core-connectivity-k8s except mysql/0 are lacking a running node_exporter process

<details>
<summary>display node_exporter processes on all vms through bosh ssh
</summary> 

```bash
INSTANCES="$(bosh vms --json | jq -r '.Tables[].Rows[].instance')"
$ echo $INSTANCES 
agents-gitlab/52f999a3-e1a0-4e11-b298-46d07d318561 agents-gitlab/54563398-1d49-44ab-bb5c-383d44bdcf8a agents-gitlab/97409491-d5a4-41b2-b804-4d63bf7bbff9 agents-gitlab/bf8e52d1-bee9-416e-b60b-1a05f5717798 agents-gitlab/fb4d91e0-e0e0-45f4-86e0-8bfa43fe8745 agents/534d1a04-3caa-46a5-81ad-c030b0302aec agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5 agents/9f17f3b2-ba64-4bbe-8476-6b733fdfa6d5 agents/a110edd7-30db-46de-b737-27dd985ef9a3 bastion-agents/1d2c99f3-a7dd-44e2-9a78-88c11f89bfc6 bastion-agents/29925004-26c6-4450-bc56-2ffbe51be73f bastion-agents/f5349c3f-9bd6-4178-a553-708623faac4d bastion-agents/fa923e7a-f8dc-4819-bbc1-6a17db85591c minio-agents/2180ffde-5718-4571-aede-684e43b191af minio-agents/37ba074b-2195-44e3-9d2f-860f924d912d minio-agents/3ba27379-6ffa-4305-8263-3d4bf55eda20 minio-agents/7212bd32-e38f-42a5-b14a-7ab8d8a2765b minio-agents/7d72f553-aa51-436f-a413-aaeac482cb47 minio-agents/ad556ace-6211-4b31-896f-beee357ef9ef minio-agents/c7c4edf4-fbf9-40b6-b8c8-fd84869b0a38 mysql/6ae4b76e-20bf-4a22-8935-02df27c5be5d server/11aa3763-7a95-47ad-8089-7399a97a2d0d
inception-integration ⚡intranet proxy ☁️  bosh-micro:00-core-connectivity-k8s ~
$ for instance in ${INSTANCES} ; do echo "processing ${instance}";  bosh ssh ${instance} -c 'sudo pstree | grep node_exporter' 2>&1 | grep -v "Running command" | grep -E "stdout|processing" ; done
processing agents-gitlab/52f999a3-e1a0-4e11-b298-46d07d318561
processing agents-gitlab/54563398-1d49-44ab-bb5c-383d44bdcf8a
processing agents-gitlab/97409491-d5a4-41b2-b804-4d63bf7bbff9
processing agents-gitlab/bf8e52d1-bee9-416e-b60b-1a05f5717798
processing agents-gitlab/fb4d91e0-e0e0-45f4-86e0-8bfa43fe8745
processing agents/534d1a04-3caa-46a5-81ad-c030b0302aec
processing agents/650ebbfa-efda-4ceb-9c8d-497ac29bc2a5
processing agents/9f17f3b2-ba64-4bbe-8476-6b733fdfa6d5
processing agents/a110edd7-30db-46de-b737-27dd985ef9a3
processing bastion-agents/1d2c99f3-a7dd-44e2-9a78-88c11f89bfc6
processing bastion-agents/29925004-26c6-4450-bc56-2ffbe51be73f
processing bastion-agents/f5349c3f-9bd6-4178-a553-708623faac4d
processing bastion-agents/fa923e7a-f8dc-4819-bbc1-6a17db85591c
processing minio-agents/2180ffde-5718-4571-aede-684e43b191af
processing minio-agents/37ba074b-2195-44e3-9d2f-860f924d912d
processing minio-agents/3ba27379-6ffa-4305-8263-3d4bf55eda20
processing minio-agents/7212bd32-e38f-42a5-b14a-7ab8d8a2765b
processing minio-agents/7d72f553-aa51-436f-a413-aaeac482cb47
processing minio-agents/ad556ace-6211-4b31-896f-beee357ef9ef
processing minio-agents/c7c4edf4-fbf9-40b6-b8c8-fd84869b0a38
processing mysql/6ae4b76e-20bf-4a22-8935-02df27c5be5d
mysql/6ae4b76e-20bf-4a22-8935-02df27c5be5d: stdout |         |-node_exporter---6*[{node_exporter}]
processing server/11aa3763-7a95-47ad-8089-7399a97a2d0d
```

</details>

https://prometheus.int-redacted.domain.org/targets?search=&scrapePool=node_exporter does not list the 00-core-connectivity-k8s vm ips address in the target exporters for the node_exporter targets


The kube-prometheus-stack isn't configured to deploy node_exporter as a daemonset

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease 
[...]
  name: kube-prometheus-stack 
  namespace: 10-prometheus 
[...]
 values:                                                                                                                                                                                                                                                                                                        
    alertmanager:                                                                                                                                                                                                                                                                                                
      enabled: false                                                                                                                                                                                                                                                                                             
    grafana:                                                                                                                                                                                                                                                                                                     
      enabled: false                                                                                                                                                                                                                                                                                             
    nodeExporter:                                                                                                                                                                                                                                                                                                
      enabled: false                                                                                                                                                                                                                                                                                             
    prometheus:                                                                                                                                                                                                                                                                                                  
      enabled: false                                                                                                                                                                                                                                                                                             
      prometheusSpec:                                                                                                                                                                                                                                                                                            
        externalLabels:                                                                                                                                                                                                                                                                                          
          cluster: 00-core-connectivity-k8s                                                                                                                                                                                                                                                                      
    prometheusOperator:                                                                                                                                                                                                                                                                                          
      logLevel: debug      
```

https://github.com/prometheus-community/helm-charts/blob/304ff15da9d49ea1f6eee4b0186dcd3f7f320fb4/charts/kube-prometheus-stack/values.yaml#L1905-L1908

Seems planned in v55 ?
https://github.com/orange-cloudfoundry/paas-templates-private/blob/e584d56ee9cad61d3451946f1c80a3989bff1b20/coab-depls/20-strimzi-kafka/template/26-install-prometheus-operator-operators.yml#L25


### Affected releases

* x.y
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
