### ISSUE TITLE
metallb-3.0.12 HelmRelease not ready

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2102]
### Expected behavior

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 

### Observed behavior

master-depls/supervision HelmRelease is not ready (chart is ok and running)
```
status:                                                                                                                                                                                                            
  conditions:                                                                                                                                                                                                      
  - lastTransitionTime: "2023-10-04T16:48:33Z"                                                                                                                                                                     
    message: HelmChart 'fluxcd/01-loadbalancer-metallb' is not ready                                                                                                                                               
    reason: ArtifactFailed                                                                                                                                                                                         
    status: "False"                                                                                                                                                                                                
    type: Ready                                                                                                                                                                                                    
  - lastTransitionTime: "2023-10-04T12:23:30Z"                                                                                                                                                                     
    message: Helm upgrade succeeded                                                                                                                                                                                
    reason: UpgradeSucceeded                                                                                                                                                                                       
    status: "True"                                                                                                                                                                                                 
    type: Released                                                                                                                                                                                                 
  failures: 2              
```
 
### Analysis

for v56, we switch to granular helm repos. And bitnami-repo is now targeting internet bitnami oci.

The problem is that bitnami do regular urge on old HelmChart, and didnt migrate all legacy to OCI.
On the other hand, paas-templates is migrating to metallb operator chart (upstream community, not bitnami). The old chart is used for legacy, waiting for migration see https://github.com/orange-cloudfoundry/paas-templates/issues/1696:
- 00-core-connectivity: the chart is installed with helmkubectl bosh release action, wired to legacy JCR aggregated helm-repo =>no visible issue
- master-depls/00-supervision uses fluxcd => gitops status is 'Not Ready', but the chart i still installed and running.

### Affected releases

* 56.0.0-rc1


<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
