### ISSUE TITLE
failure compiling mongodb-osb (sticked version to bionic stemcell)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#2103]
### Expected behavior

* As a paas-templates operator 
* In order to upgrade to v56
* I need to have mongodb-osb upgrade ok

## references
- #1955 
- https://github.com/cloudfoundry/bosh/issues/2190
- https://github.com/orange-cloudfoundry/cf-ops-automation/pull/438
- Related to https://github.com/orange-cloudfoundry/paas-templates/issues/991 after fixing missing sources

### Observed behavior
 
```
Task 5308906 | 18:59:44 | Error: 
Can't use release 'routing/0.262.0'. It references packages without source code and are not compiled against stemcell 'bosh-vsphere-esxi-ubuntu-bionic-go_agent/1.174':
 - 'golang-1.20-linux/274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5'
 - 'route_registrar/f557d2a73846eba236bf24b8427d390bb2e2adecaf0743743553132341925a3e'
 - 'routing_utils/e9ae78584c5fc09dd6c769ccc198cf272bf020aa337675fcfc9707a991b7de0b'

```

### Affected releases

* 56.0.0
* earlier versions

**Comment by o-orand** [comment]
Workaround: 
 - bosh upload-release routing/0.262.0
 
This workaround leads to 
```
Task 26766053 | 13:28:34 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 26766053 | 13:28:34 | Compiling packages: vault/6e242f04f2355d30b5f9e762509215dfa714ae6e15a1c28e35e2ec051dda468f
Task 26766053 | 13:28:34 | Compiling packages: nginx/168ab523ea5927456787074307be59d0db01cdef5dd00c5610ca9490cc72f5af
Task 26766053 | 13:29:53 | Compiling packages: vault/6e242f04f2355d30b5f9e762509215dfa714ae6e15a1c28e35e2ec051dda468f (00:01:19)
Task 26766053 | 13:29:53 | Compiling packages: sqlite3/e2ac5026327c3721d14a92b0a1a0a7bcd97a277719e0ade506051e0511fb9f51
Task 26766053 | 13:30:02 | Compiling packages: nginx/168ab523ea5927456787074307be59d0db01cdef5dd00c5610ca9490cc72f5af (00:01:28)
Task 26766053 | 13:30:02 | Compiling packages: golang-1.20-linux/274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5 (00:00:15)
                     L Error: Action Failed get_task: Task dba89143-cd47-4616-4343-5e3c2d97ed68 result: Compiling package golang-1.20-linux: Fetching package golang-1.20-linux: Fetching package blob c00e7fd5-94fc-4c6a-bc07-b6d01f2fb4bc: Getting blob from inner blobstore: Checking downloaded blob 'c00e7fd5-94fc-4c6a-bc07-b6d01f2fb4bc': Expected stream to have digest 'sha256:3b0b9780a55a6f3c477875adb3483ebe7027c2a366a1f59d105087e3a30206be' but was 'sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992'
Task 26766053 | 13:31:36 | Compiling packages: sqlite3/e2ac5026327c3721d14a92b0a1a0a7bcd97a277719e0ade506051e0511fb9f51 (00:01:43)
Task 26766053 | 13:31:45 | Error: Action Failed get_task: Task dba89143-cd47-4616-4343-5e3c2d97ed68 result: Compiling package golang-1.20-linux: Fetching package golang-1.20-linux: Fetching package blob c00e7fd5-94fc-4c6a-bc07-b6d01f2fb4bc: Getting blob from inner blobstore: Checking downloaded blob 'c00e7fd5-94fc-4c6a-bc07-b6d01f2fb4bc': Expected stream to have digest 'sha256:3b0b9780a55a6f3c477875adb3483ebe7027c2a366a1f59d105087e3a30206be' but was 'sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992'
```

As it is the first deployment using `routing/0.262.0`, we can use bosh recreate to restore previous state, delete release and process again.

**Comment by JCL38-ORANGE** [comment]
Force COA pre-compilation mongodb bosh release both on bosh-ops and bosh-coab (by default pre-compilation is only performed on bosh-ops)

**Comment by o-orand** [comment]
We discover an conflict in routing/0.262 and bosh-dns/1.36.1 on sha256:
 
Commit id `274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5`:
 - on bosh-dns: https://github.com/search?q=repo%3Acloudfoundry%2Fbosh-dns-release%20274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5&type=code
 - on rounting release: https://github.com/search?q=repo%3Acloudfoundry%2Frouting-release%20274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5&type=code

[golang-1-linux](https://github.com/cloudfoundry/bosh-dns-release/tree/62b175cba0d3972ec2927a5ba9333143dd41c92d/.final_builds/packages/golang-1-linux) on [bosh-dns-1.36.1](https://github.com/cloudfoundry/bosh-dns-release/blob/62b175cba0d3972ec2927a5ba9333143dd41c92d/.final_builds/packages/golang-1-linux/index.yml#L30-L33): `sha1: sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992`
```
  274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5:
    version: 274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5
    blobstore_id: b14ab1f0-8a3e-400d-417f-bfc5f49599df
    sha1: sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992
```


[golang-1.20](https://github.com/cloudfoundry/routing-release/blob/5925720c95a018217ca80696f28738d075621f63/.final_builds/packages/golang-1.20-linux/) on [routing-0.262.0](https://github.com/cloudfoundry/routing-release/blob/5925720c95a018217ca80696f28738d075621f63/.final_builds/packages/golang-1.20-linux/index.yml#L2-L5) :  `sha1: sha256:3b0b9780a55a6f3c477875adb3483ebe7027c2a366a1f59d105087e3a30206be`
```
  274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5:
    version: 274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5
    blobstore_id: 3f385c7e-437f-47b6-62fe-257a870dd8e3
    sha1: sha256:3b0b9780a55a6f3c477875adb3483ebe7027c2a366a1f59d105087e3a30206be
```

[routing-golang-1-linux](https://github.com/cloudfoundry/routing-release/blob/a3244aca571fcb79ab876f0dd26bbed13d89b958/.final_builds/packages/routing-golang-1-linux/
) on [routing-0.262](https://github.com/cloudfoundry/routing-release/blob/a3244aca571fcb79ab876f0dd26bbed13d89b958/.final_builds/packages/routing-golang-1-linux/index.yml#L10-L13
): `sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992`
```
  274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5:
    version: 274ac7c419ab40ed71a24a859bc594bb62b88980fb0bdbb74750c2b979a777d5
    blobstore_id: b33a3e0c-97c1-4d6e-7db9-fbaedb68f008
    sha1: sha256:5d7b0597a5b311bedbdd99c21bbf2a9b5db9631b2d2668a7a7c5d43882beb992
```

We bumped routing release to `0.274.0` and disable cache for routing on COAB and Ops root deployments precompile.
