### ISSUE TITLE
v56.0.1: 95-shared-services-datastore bucket job fails: missing remote-s3-secret

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2142]
### Expected behavior

* As a paas-templates operator
* In order to have backups for 00-k8s-ha-datastore
* I need the bucket to be created

### Observed behavior

 bucket job fails: missing remote-s3-secret

```
  initContainerStatuses:                                                                                                                                                                                           
  - image: minio/mc:RELEASE.2023-03-23T20-03-04Z                                                                                                                                                                   
    imageID: ""                                                                                                                                                                                                    
    lastState: {}                                                                                                                                                                                                  
    name: mccli                                                                                                                                                                                                    
    ready: false                                                                                                                                                                                                   
    restartCount: 0                                                                                                                                                                                                
    state:                                                                                                                                                                                                         
      waiting:                                                                                                                                                                                                     
        message: secret "remote-s3-secret" not found                                                                                                                                                               
        reason: CreateContainerConfigError    
```

### Affected releases

* x.y
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
