### ISSUE TITLE
v56.0.1: Polluting error about failed missing kustomization for active profile `82-r4-vsphere` in ha-datastore

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2143]
### Expected behavior

* As a paas-templates operator
* In order to deploy v56.0.1
* I need the `check-k8s` to not return errors

### Observed behavior

Polluting about failed missing kustomization for active profile `82-r4-vsphere` in ha-datastore

```
"ha-datastore" suspended/failed resources...                                                                                                                                                                       
                                                                                                                                                                                                                   
READY  SUSP.  KIND             NAMESPACE/NAME                                                                                                                                                                      
False  False  kustomization    fluxcd/paas-k8s-gitops-kustomization-82-r4-vsphere  
```

```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2                                                                                                                                                                    
kind: Kustomization                                                                                                                                                                                                
[...]
  name: paas-k8s-gitops-kustomization-82-r4-vsphere                                                                                                                                                                
  namespace: fluxcd                                                                                                                                                                                                
[...]
spec:                                                                                                                                                                                                              
[...]
  path: ops-depls/00-k8s-ha-datastore/k8s-config/manifests/00-flux-kustomizations-82-r4-vsphere              
[...] 
 - lastTransitionTime: "2023-10-31T11:06:29Z"                                                                                                                                                                     
    message: 'kustomization path not found: stat /tmp/kustomization-3021192418/ops-depls/00-k8s-ha-datastore/k8s-config/manifests/00-flux-kustomizations-82-r4-vsphere:                                            
      no such file or directory'                                                                                                                                                                                   
    observedGeneration: 1                                                                                                                                                                                          
    reason: ArtifactFailed                                                                                                                                                                                         
    status: "False"                                                                                                                                                                                                
    type: Ready                                                                                                                                                                                                    
```

### workaround

ignore the error


### Affected releases

* x.y
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
