### ISSUE TITLE
check-k8s improvement to detect pending Load balancer services

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2164]
### Expected behavior

* As a paas-templates operator
* In order to ease checking the state of a k8s cluster when no observability infrastructure is available (Prometheus is not reacheable/ or broker) 
* I need pending k8s services to be reported by the  check-k8s

### Observed behavior
 
#2163

Successful loadbalance service status
```yaml
status:                                                                                                                                                                                                    
  loadBalancer:                                                                                                                                                                                            
    ingress:                                                                                                                                                                                               
    - ip: 192.168.116.11   
```	
	
Pending loadbalance service status
```yaml
status:                                                                                                                                                                                                    
  loadBalancer: {}   
```

### Affected releases

* 56.0.2
* earlier versions
