### ISSUE TITLE
CPUThrottlingHigh alert on coab mysql containers: too low cpu limits 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2171]
### Expected behavior


* As a paas-templates operator
* In order to focus on production issues
* I need that failing alert relate to operational issues that need care

### Observed behavior

CPUThrottlingHigh alert triggers

![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/b24c10cc-9682-4ac5-99f5-3d077b243994)
[detailed alerts](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/65c7abe5-70c3-41a6-a33b-a1a97b46ae7b)


Too low limit set on some coab DBO mysql containers ?
```yaml
   image: database-virt-docker-stable.repos.tech.orange/orange-mariadb-sidecar:10.6.15-ubuntu20-2                                                                                                                 
    imagePullPolicy: IfNotPresent                                                                                                                                                                                  
    name: s3binlog                                                                                                                                                                                                 
    resources:                                                                                                                                                                                                     
      limits:                                                                                                                                                                                                      
        cpu: 50m                                                                                                                                                                                                   
        memory: 100Mi                                                                                                                                                                                              
      requests:                                                                                                                                                                                                    
        cpu: 10m                                                                                                                                                                                                   
        memory: 64Mi 
```

https://runbooks.prometheus-operator.dev/runbooks/kubernetes/cputhrottlinghigh/

> The alert is purely informative and unless there is some other issue with the application, it can be skipped.
> 
> Notice: User shouldn’t increase CPU limits unless the application is behaving erratically (another alert firing).
> 
> For this particular reason, the alert is inhibited by default in kube-prometheus and can be sent only if another alert in the same namespace is firing.
> 



### Workaround

ignore the alert
 
### Affected releases

* 56.0.1
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
