### ISSUE TITLE
v56.0.2 fails to upgrade prometheus-stack to 45.9.1

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2188]
### Expected behavior

* As a paas-templates operator
* In order to deploy v56, 
* I need 00-core-connectivity to succeed

### Observed behavior
 
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/28f294d8-87ba-46a2-9a2d-f1f1c37128fb)


```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1                                                                                                                                                                         
kind: HelmRelease                                                                                                                                                                                                  
metadata:                                                                                                                                                                                                          
  name: kube-prometheus-stack                                                                                                                                                                                      
  namespace: 10-prometheus                                                                                                                                                                                         
[...]
  - lastTransitionTime: "2023-11-17T13:42:01Z"                                                                                                                                                                     
    message: |-                                                                                                                                                                                                    
      Helm upgrade failed: cannot patch "kube-prometheus-stack-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "kube-prometheus-stack-prometheus-node-exporter" is invalid: spec.selector: Invalid va
lue: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kube-prometheus-stack", "app.kubernetes.io/name":"prometheus-node-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)
}: field is immutable                                                                                                                                                                                              
                                                                                                                                                                                                                   
      Last Helm logs:                                                                                                                                                                                              
                                                                                                                                                                                                                   
      preparing upgrade for kube-prometheus-stack                                                                                                                                                                  
      resetting values to the chart's original version                                                                                                                                                             
      performing update for kube-prometheus-stack                                                                                                                                                                  
      creating upgraded release for kube-prometheus-stack                                                                                                                                                          
      warning: Upgrade "kube-prometheus-stack" failed: cannot patch "kube-prometheus-stack-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "kube-prometheus-stack-prometheus-node-exporter" is invali
d: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"kube-prometheus-stack", "app.kubernetes.io/name":"prometheus-node-exporter"}, MatchExpressions:[]v1.L
abelSelectorRequirement(nil)}: field is immutable                                                                                                                                                                  
    reason: UpgradeFailed                                                                                                                                                                                          
    status: "False"                                                                                                                                                                                                
    type: Released 
```

### Root cause

Prometheus bumped into 
https://github.com/orange-cloudfoundry/paas-templates-private/pull/1963

### Affected releases

* x.y
* earlier versions

<!--
### Traces and logs

Remember this is a public repo. DON'T leak credentials or Orange internal URLs. 
Automation may be applied in the future. 

* [ ] I have reviewed provided traces against secrets (credentials, internal URLs) that should not be leake, manually of using some tools such as [truffle-hog file:///user/dxa4481/codeprojects/mytraces.txt](https://github.com/dxa4481/truffleHog#truffle-hog)
 -->
