### ISSUE TITLE
setup-upgrade-pipeline/auto-reload-from-git: excessive pipeline cleanup

### ISSUE THREAD

**Issue by o-orand** [orange-cloudfoundry/paas-templates#2191]
### Expected behavior

* As a paas-templates operator 
* In order to have history on QA platform
* I need to customize upgrade pipeline retention

### Observed behavior
Pre merge step described in [release-notes/V56_0_2.md](https://github.com/orange-cloudfoundry/paas-templates-private/blob/3008cd38d2907cd7e9fd0b75e3e6fc3a0a90f4cd/zz-docs/release-notes/V56_0_2.md#L250-L250) does not work

```
#### Pre-merge steps (before updating reference branch)
If default pipeline cleanup policy is not suitable for your use case, please adjust it

Create a file in secret repository at `bootstrap/setup-upgrade-pipeline/secrets/secrets.yml`

#Default values below:
secrets:
  coa:
    max-pipelines: 2 
    max-patch-pipelines: 1
  paas-templates:
    max-pipelines: 2
    max-patch-pipelines: 1

``` 

Secrets loading is ignored by `auto-reload-from-git` job

### Affected releases

* 56.0.2
