### ISSUE TITLE
Document static CIDR ranges (~IPAM)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2217]
### Expected behavior 

* As a paas-templates operator 
* In order to quickly identity from an IP address the following 
   * A bosh VM
      * An associated bosh network
          * As associated root deployment
   * a K8S pod
      * an associated k8s cluster hosting this pod
   * a K8S load balancer service
      * an associated k8s cluster hosting this service
* I need 
    * manually documented CIDR ranges 
    * a dynamic IPAM/CIDR range 

<!--
and

* As a paas-templates operator | cf user | marketplace user | osb service provider | paas-templates author | paas-templates maintainer
* In order to 
* I need 
 -->

### Observed behavior

The bosh IPAM is documented into the private reference documentation for each version

The K8S CIDR range is not yet documented

<!--
<details>

<summary></summary>
 
</details>
-->

### Workaround

Look at source code or associated K8S CR:
* for cilium CNI: clusterPoolIPv4PodCIDRList in flux HelmRelease values
* for default k8s cluster
   * https://github.com/orange-cloudfoundry/k3s-boshrelease/blob/a21f1d95c0284446a1b1ad58f9cc247e47171655/jobs/k3s-
server/spec#L218-L224
   * k8s node metadata: spec.podCIDRs

```yaml
spec:                                                                                                                                                                                                                                                                                                            
  podCIDR: 10.42.0.0/24                                                                                                                                                                                                                                                                                          
  podCIDRs:                                                                                                                                                                                                                                                                                                      
  - 10.42.0.0/24 
```

<!-- hint: document how the impacted actor may workaround the issue  -->
* 

### Possible fixes

<!-- hint: document how a feature branch could address the feature or issue -->

* Create a grafana dashboard with https://github.com/kubernetes/kube-state-metrics/blob/main/docs/node-metrics.md

<html><body>
<!--StartFragment--><h1 tabindex="-1" dir="auto">Node Metrics</h1>

Metric name | Metric type | Description | Unit (where applicable) | Labels/tags | Status
-- | -- | -- | -- | -- | --
[...]
kube_node_info | Gauge | Information about a cluster node |   | node=\<node-address\>  kernel_version=\<kernel-version\>  os_image=\<os-image-name\>  container_runtime_version=\<container-runtime-and-version-combination\>  kubelet_version=\<kubelet-version\>  kubeproxy_version=\<kubeproxy-version\>  pod_cidr=\<pod-cidr\>  provider_id=\<provider-id\>  system_uuid=\<system-uuid\>  internal_ip=\<internal-ip\> | STABLE

<!--EndFragment-->
</body>
</html>Node Metrics


### Affected releases and environments

* affects release: 56.0.3
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

### Related work

#2216 


<!--
