### ISSUE TITLE
All Grafana datasources have incorrect configured scrape interval, resulting use of $__rate_interval to return no data

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2219]
### Bug Impact 

* As a paas-templates operator | paas-templates author 
* This bug prevents me to use the $__rate_interval in custom dashboards
* This bug prevents me to leverage off-the-shelf dashboards using the $__rate_interval 

### Observed behavior

![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/c056e4ec-011d-4d16-81ac-be145990e666)

* 

### Workaround

* Manually fix it in the grafana datatsource config
![image](https://github.com/orange-cloudfoundry/paas-templates/assets/4748380/eb4aa66e-4c10-446c-9fc5-6b2ede44e53d)

### Possible fixes

```yaml
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-serv-grafanadatasource
spec:
  name: middleware.yaml
  datasources:
    - name: DS_PROMETHEUS_SERV
      type: prometheus
      access: proxy
      url: http://prometheus.10-prometheus:9090
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
```

* [ ] Set timeInterval to a value consistent with scraping times
   * [ ] Compute typical scrape times from source code:
```
 grep  --no-filename -ri 'scrape_interval: ' | sort | uniq -c | sort -nr
     35       scrape_interval: 5m
     26       scrape_interval: 2m
     17       scrape_interval: 120s
     15           scrape_interval: 5m
      7     scrape_interval: 5m
      6       scrape_interval: 4m
      5             scrape_interval: 5m
      2         scrape_interval: 5m
      2             scrape_interval: 30m #should be more
      1       scrape_interval: 60s
      1         scrape_interval: 60s
      1 #    scrape_interval: 5m
      1       scrape_interval: 1m #same duration as bosh scrapping on prometheus-exporter-coab
      1     scrape_interval: 1m
```
### Reference

https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/

### Affected releases and environments

* affects release: 56.0.3
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--
