### ISSUE TITLE
Add dashboard and alerting on (failed) service instances status

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#225]
### Expected behavior

As a user, I expect failures of asynchronous services (such as COAB) to be handled by operators without having to report them.

### Observed behavior

Currently, operators are not notified upon failure of service instances or service bindings.

* [x] The cf exporter does expose service instance last operation state, see https://github.com/bosh-prometheus/cf_exporter/issues/29 
* [ ] coab is not yet exposing additional metrics such as human readeable names , see related https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/150

* [ ] The prometheus [service dashboard](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/cloudfoundry_dashboards/templates/cf_services.json) does not yet include service type and status.

See POC, need refinements
![image](https://user-images.githubusercontent.com/4748380/71126104-97bb8680-21e8-11ea-8eac-852ad8ea4b08.png)

* [x] The [prometheus alerts](https://github.com/bosh-prometheus/prometheus-boshrelease/tree/master/jobs/cloudfoundry_alerts/templates) does not include service last operation alert

### Affected release

Reproduced on version 36.x
 -->

**Comment by poblin-orange** [comment]
cc @CDallosto-orange do you want to contribute this ?

**Comment by CDallosto-orange** [comment]
> cc @CDallosto-orange do you want to contribute this ?

Of course 👍

**Comment by Guilamb** [comment]
https://github.com/bosh-prometheus/cf_exporter#metrics

Dashboard
* [ ] Add plan name, instead of plan id for `cf create-service_instance" per service plan id` on grafana
* [ ] Set the status label in red when `last operation state` is "failed"
* [ ]  set bottom table panel title  `last operation details`
* [ ]  keep configureable time range for all dashboards, and set default time to 2D

```
  - alert: CFExporterServiceInstanceLastOperationState
        expr: sum(cf_service_instance_info{last_operation_state="failed"}) by (service_instance_name) != 0
        for: 1m
        labels:
          service: cf-exporter
          severity: critical
        annotations:
          summary: "cf_exporter `{{$labels.service_instance_name}}` Service Instances Last Operatoin Failed"
          description: "cf_exporter `{{$labels.service_instance_name}}` failed to instanciate"
```          

Alert
* [ ]  tun the alert message wiht as much details as possible such as `osb request of type { provision  | update | unprovision } failed for service instance with guid {} and service name {} and  service plan name {} provisionned from osb-cmdb org {}  with annotations { ...} `
