### ISSUE TITLE
k9s color theme in bastion should follow environment conventions to prevent confusions among envs

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2257]
### Expected behavior 

* As a paas-templates operator 
* In order to prevent accident in production #2249 
* I need that 
   * the visual theme in k9s distinguishes between prod/pre-prod/int
   * the visual theme is consistent with the one used in portal and bastion shell

### Observed behavior

Same default k9s theme in all environments

### References

https://github.com/derailed/k9s#skins
> You can style K9s based on your own sense of look and style. Skins are YAML files, that enable a user to change the K9s presentation layer. 

https://github.com/derailed/k9s/blob/master/skins/red.yaml
```yaml
# -----------------------------------------------------------------------------
# Red skin
# -----------------------------------------------------------------------------

# Skin...
k9s:
  body:
    fgColor: red
    bgColor: black
    logoColor: red
```

### Workaround

* 

### Possible fixes

* 

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--
