### ISSUE TITLE
During upgrade pipeline, paused fluxcd gitrepo trigger false positive alert

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#2260]
### Bug Impact 

* As a paas-templates operator 
* This bug distracts me from real problems to foc

and

* As a paas-templates operator 
* In order to deploy v56.0.4 
* I need triggered alerts to indicate problem to address

### Observed behavior

teams/main/pipelines/paas-templates-56.0.4-upgrade/jobs/check-alerts-after-master-depls-upgrade/builds/1 fails with all kustomizations failing:

```
ReconciliationFailure  2024-01-29 15:19:08 UTC  Kustomization 00-marketplace-fluxcd/paas-k8s-gitops-kustomization reconciliation has been failing for more than ten minutes.                                    active  

ReconciliationFailure  2024-01-29 15:19:08 UTC  Kustomization 00-marketplace-fluxcd/00-common reconciliation has been failing for more than ten minutes.                                                        active  
```

### Root cause

During upgrade pipeline, the next root-deployments have their GitRepo CR paused by the upgrade pipeline.

When the upgrade includes a stemcell bump, the cached gitrepo flux source artefacts are cleared and the source controller now returns 404 status to the suspended resources even though its status indicates successfully stored artefact

```yaml
  conditions:
  - lastTransitionTime: "2024-01-22T16:38:11Z"
    message: stored artifact for revision 'master@sha1:4556e337d5542ebd6b76914eae7a7ccab76f0863'
    observedGeneration: 42
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-01-22T16:38:11Z"
    message: stored artifact for revision 'master@sha1:4556e337d5542ebd6b76914eae7a7ccab76f0863'
    observedGeneration: 41
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
```

* 

### Workaround

* Just ignore the alert

### Possible fixes

* #1936 to get more user friendly status/source controller messages
* [ ] automatically pause Kustomizations ??

### Affected releases and environments

* affects release: x.y
* affects iaas-type: all | vsphere | openstack
* affects environment: all | integration (openstack) | integration (vsphere) | preprod | prod

<!--
