### ISSUE TITLE
stratos cf app startup failure

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#263]
### Observed behavior
timeout when cf push.

### Affected release

Reproduced on version 37.0.1
hotfix applied on v37
hot fixed merged in v38.0.0

**Comment by gberche-orange** [comment]
The workaround applied in 1b21a0d1333b42956deab12a069743f65dee9e59 is incorrect:

```yml
---
applications:
- name: stratos-ui-v2
  path: stratos-ui-v2
  host: console-v2
  domain: (( grab secrets.cloudfoundry.system_domain ))
  buildpack: https://github.com/cloudfoundry-incubator/stratos-buildpack#v2
  memory: 1536M
  disk_quota: 1024M
  timeout: 180
  health-check-type: port
  env:
    CF_STAGING_TIMEOUT: 30  #--- Extends staging timeout from defaut (15 min)
    CF_STARTUP_TIMEOUT: 30  #--- Extends startup timeout from defaut (5 min)
    CF_API_FORCE_SECURE: true
    FORCE_HTTPS: true
```

The `CF_STAGING_TIMEOUT` environment variable needs to be exported before invoking the CF CLI, and not as application environment variables

See  https://cli.cloudfoundry.org/en-US/cf/push.html and associated unit tests for details of the CLI support for `CF_STAGING_TIMEOUT`
https://github.com/cloudfoundry/cli/blob/e9a43b088180518b329f7a609975a4a868395af8/util/configv3/env_test.go#L44-L62
https://github.com/cloudfoundry/cli/blob/b6a3695a5db06d6628428067e0a78e63041ea1ca/cf/commands/application/start.go#L98-L116

The COA build does not yet the https://github.com/concourse/cf-resource resource, and instead directly invokes the cf cli as a concourse task https://github.com/orange-cloudfoundry/cf-ops-automation/blob/4e1174f76152977f2ad67de9b3a68afe65714cd1/scripts/cf/push.sh#L52-L64
