### ISSUE TITLE
credhub - k8s interopability

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#387]
### Expected behavior
As a platform operator, i want the paas-templates k8s workload to share secrets management with bosh workload

see https://www.youtube.com/watch?v=uevyVtnPOwI

**Comment by poblin-orange** [comment]
A possible solution is to use credhub generated root ca, and let k8S generate and rotate its local secrets, with certmanager.

pro:
- easy to setup
- limited interoperability between bosh credhub and k8S

cons:
- cant benefit from prometheus credhub exporter and alerting for k8s secrets
- limited control of cert rotation: automated, but unclear if it does indeed restart the pod to take the new certs.

**Comment by obeyler** [comment]
> cant benefit from prometheus credhub exporter and alerting for k8s secrets
I'm not agree as we can also add an alerting inside the prometheus inside K8S 
We already must agreagate the prometheus of CFCR master/micro/obs into Prometheus   created by bosh
example of how obtain a certificate update 
```
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: Certificate
      metadata:
        name: certificate-openldap
        namespace: openldap
      spec:
        secretName: secret-openldap-tls-cert
        duration: 24h
        renewBefore: 12h
        commonName: openldap.openldap.svc.cluster.local
        issuerRef:
          name: issuer-openldap
          kind: Issuer
```
