### ISSUE TITLE
refactor bosh cli to avoid secrets.yml editions for bumps

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#415]
### Expected behavior

As a service operator, in order to use the latest [orange-cf-bosh-cli](https://github.com/orange-cloudfoundry/orange-cf-bosh-cli) jumpbox without manually editing its associated , I need the bosh-cli container versions to be automated.

As a paas-templates author, in order to provide support to [orange-cf-bosh-cli](https://github.com/orange-cloudfoundry/orange-cf-bosh-cli) users, I need the container image to be versionned and automatically deployed along with paas-templates

### Observed behavior

for each admin users entries in `micro-depls/docker-bosh-cli/secrets/secrets.yml` file in secrets repository, need update, commit and push with the following content

```yml
properties:
  containers:
  - name: datacontainer
    image: orangecloudfoundry/orange-cf-bosh-cli:2.1.34
    bind_volumes:
    - "/data"
    volumes:
    - "/etc/ssl/certs:/etc/ssl/certs:ro"

  - name: <admin_account>
    hostname: <admin_account>
    image: orangecloudfoundry/orange-cf-bosh-cli:2.1.34
...
```

This list of containers is directly used by 
https://github.com/orange-cloudfoundry/paas-templates/blob/a992ea557873e36f4381914d257de02ca2a346a1/micro-depls/docker-bosh-cli/template/docker-bosh-cli-tpl.yml#L39-L41

### Affected release

Reproduced on version 41.x

### Possible implementations

* Use an idempotent shell script (such as a sed command within a [post-generate.sh](https://github.com/orange-cloudfoundry/cf-ops-automation#bosh-deployment-resources-template-format) hook) to automatically bump the container version in the `micro-depls/docker-bosh-cli/secrets/secrets.yml` file
* Convert `micro-depls/docker-bosh-cli/secrets/secrets.yml` into a spruce file such as `micro-depls/docker-bosh-cli/secrets/secrets-tpl.yml`, which would load the container version from a paas-templates provided file.
   * In order to avoid manual migration, consider an idempotent script which applies the above conversion on the fly.
      * through a [post-generate.sh](https://github.com/orange-cloudfoundry/cf-ops-automation#bosh-deployment-resources-template-format) hook ? See [sample](https://github.com/orange-cloudfoundry/cf-ops-automation/blob/develop/spec/tasks/generate_manifest/additional-resource/a-root-depls/post-generate.sh#L3)

/CC @o-orand @ogrand
