### ISSUE TITLE
Parallel stemcell upgrade fails on compilation vm IP source shorteage

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#451]
### Expected behavior

As a paas-templates operator, in order to bump stemcell quickly upon cve, I'd like to parallelize bosh deployments in root deployments including those that require to compile packages.

Relates to #44 

### Observed behavior

When deploying v41 and unpausing jobs in ops-depls, deployment fail with message

```
 Compiling packages: utils/66ca3e6c236837854d49102f4cf55896cea248f4 (00:00:00)
                      L Error: Failed to reserve IP for 'compilation-d2defeac-801e-436b-b46d-306e49e937d3/c76e5cf6-5e2c-469e-a6d5-125afd986b55 (0)' for manual network 'compilation-network': no more available
```

Looking at bosh deployments while concurrent compilation occur show  not started vms potentially consumming IP addresses

```
$ for d in admin-ui cassandra cf-rabbit cf-redis cf-riak-cs cloudfoundry-mysql io-bench kafka memcache mongodb neo4j-docker nfs-volume postgresql-docker vault ; do bosh -d $d instances | grep compilation; done
compilation-8d92d184-436f-4b81-be59-ddd18847363f/e9f44038-fc94-42cc-9b83-2a4e89145526   -       z1      -
compilation-fd9fe045-51c8-4bbf-9c81-43da9d7a53ed/5560fb8a-bc62-45eb-88af-01149cf687e2   -       z1      -

compilation-90f35af3-f67c-4b7a-bbf9-f51dbdae3910/ff3a01b2-8954-404b-b89b-5bd666833be8   running z1      192.168.100.63`
compilation-dc575092-1a6e-401c-85f5-e16e9ea1bf83/32a34639-fdf1-4908-a3b6-8b2323529e15   running z1      192.168.100.62
compilation-ece61075-a92d-48ff-ba50-322c40a35a9a/30955fd8-c088-4931-90d3-9b0c37748799   running z1      192.168.100.61


compilation-0f964165-0ca8-41aa-98eb-a399b9f10098/2795ba4a-9d3a-46bb-a524-e601a8ddfc56   -       z1      -
compilation-d8f28dca-23f7-4ba7-b318-e0aa1df090fc/9144db66-7976-40fc-9bf9-e156e115e1d7   -       z1      -
compilation-42b064bb-da6a-46a8-a7ca-142a669bdbb6/fda25b57-4993-440f-b6a8-d4e0394cf00d   -       z1      -

```

The compilation network was segmented into slots to workaround lack of dhcp support on vsphere

```
#--- Compilation network
- name: compilation-network
  type: manual
  subnets:
  - range: 192.168.100.0/24
    gateway: 192.168.100.1
    dns: ((dns))
    azs: [z1,z2]
    reserved:
    - 192.168.100.2 - 192.168.100.60
    - 192.168.100.81 - 192.168.100.254


compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: compilation-network
```

### Workaround:

Add pauses between each job to avoid concurrent compilation (20 min below)

```bash
~/bosh/template/admin/unpause-jobs.sh -p ops-depls-bosh-generated --wait 1200
```

### Affected release

Reproduced on version 41.x
