### ISSUE TITLE
credhub seeding mechanism triggers useless bosh deployments

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#504]
### Expected behavior
As a platform operator, i dont want useless bosh deploy triggered by credhub-seeding mechanism

### Observed behavior

As of v42, each credhub seeding job reimports every shared-secrets.yml originating secrets in credhub (even if unchanged, generating new versions of the secrets). This loads crehub db, and triggers bosh deploys actions.

**Comment by poblin-orange** [comment]
example on integration env. more than 5 value versions per day: 

```
poblin@fe-int:~$ credhub get -n /secrets/cloudfoundry_system_domain --versions=5 
versions:
- id: dbf2dc2c-a93a-4c38-b392-79d0d41f71db
  name: /secrets/cloudfoundry_system_domain
  type: value
  value: xxx
  version_created_at: "2019-07-23T13:02:58Z"
- id: 01bbbe8a-e9a8-4acf-9b46-8c7632b61615
  name: /secrets/cloudfoundry_system_domain
  type: value
  value: xxx
  version_created_at: "2019-07-23T12:34:35Z"
- id: 4f4e8649-11c6-4d4f-ba37-a57b42d9d073
  name: /secrets/cloudfoundry_system_domain
  type: value
  value: xxx
  version_created_at: "2019-07-23T12:20:03Z"
- id: f001bcc0-5ae6-4e77-9d40-cd4373718120
  name: /secrets/cloudfoundry_system_domain
  type: value
  value: xxx
  version_created_at: "2019-07-23T10:43:01Z"
- id: 0b71e62f-2c0d-4041-85c4-c4ce461ddbc2
  name: /secrets/cloudfoundry_system_domain
  type: value
  value: xxx
  version_created_at: "2019-07-23T09:47:27Z"

```
