### ISSUE TITLE
Logsearch-ops platform/Kibana : The kibana index patern is not properly configured

### ISSUE THREAD

**Issue by wdesplas** [orange-cloudfoundry/paas-templates#560]
### Expected behavior
In the kibana configuration will be able to retrieve and display the platform logs.

### Observed behavior
In the kibana configuration for logsearch-ops is  configured to retrieve the app logs instead of the platform logs.

### Affected release

Reproduced on version 42.0
 
### Traces and logs
The file 1-kibana-tuning-operators.yml must contains :
```
---
- type: replace
  path: /instance_groups/name=upload-kibana-objects/properties?/kibana_objects/upload_patterns
  value:
    - {type: index-pattern, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/index-pattern/logs-platform.json}
    - {type: config, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/config/*.json}
    - {type: search, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-*.json}
    - {type: visualization, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-*.json}
    - {type: dashboard, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-*.json}

- type: replace
  path: /instance_groups/name=kibana/jobs/name=kibana/properties/kibana/default_app_id?
  value: dashboard/Platform-Overview
```

instead of :
```
---
- type: replace
  path: /instance_groups/name=upload-kibana-objects/properties?/kibana_objects/upload_patterns
  value:
    - {type: index-pattern, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/index-pattern/logs-app.json}
    - {type: config, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/config/*.json}
    - {type: search, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-*.json}
    - {type: visualization, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-*.json}
    - {type: dashboard, pattern: /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-*.json}

- type: replace
  path: /instance_groups/name=kibana/jobs/name=kibana/properties/kibana/default_app_id?
  value: dashboard/App-Overview
```
