### ISSUE TITLE
coab instances deployment name RFC-1123 compatibility

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#803]
### Expected behavior

* As a paas-templates  paas-templates author 
* In order to be able to construct hybrid coab services (k8s to host broker and dataplane access layer, statefull backend as bosh deployment) 

* I need  to be able to reach bosh vms with predictible DNS (bosh-dns alias), with k8s ExternalName Service mechanism

### Observed behavior

Seems the bosh-dns alias generated are not DNS compliant (seems induced by COA bosh deployment naming, including a _ character)

```
The Service "kibana-external-name-service" is invalid: spec.externalName: Invalid value: "0.kibana.tf-net-osb-data-plane-dedicated-priv.o_36194997-e031-47de-a9a0-1b490dfa4a74.bosh": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')


```
Note discussion on k8s repo (DNS RFC versus hostname RFC compatibility of ExternalName):
- https://github.com/kubernetes/kubernetes/issues/52266

cc @gberche-orange @obeyler  

### Affected releases

* 46.0.0

* earlier versions

**Comment by JCL38-ORANGE** [comment]
https://github.com/orange-cloudfoundry/cf-ops-automation-broker/issues/299

**Comment by poblin-orange** [comment]
fixed in coab 0.30, included in paas-templates 47.0.2

**Comment by gberche-orange** [comment]
@poblin-orange potential pending associated work to support migration of existing instances where the deployment name will be changed by using the coab broker property and coab-vars.yml could be updated in a future `cf update-service` coab support

/CC @JCL38-ORANGE

**Comment by gberche-orange** [comment]
@poblin-orange @JCL38-ORANGE would a simpler alternative be to use the variable holding service guid (`instance_id`or `parameters.x-osb-cmdb.labels.brokered_service_instance_guid` in the FQDN instead of the `deployment_name` ?

```yml
deployment_name: "cf-mysql"
instance_id: "7d6f72c4-7e93-432d-a2b2-9577a2eb4dd3"
service_id: "noop-ondemand-service"
plan_id: "plan-coab-mariadb-small"
context:
  platform: "cloudfoundry"
  user_guid: "321ae0c8-1289-4e49-9aa4-4fca806754f1"
  space_guid: "41450901-d400-47f8-aab4-f3095c18ac72"
  organization_guid: "018ee7d1-c4d4-4975-84e9-f92610ef5306"
parameters:
  x-osb-cmdb:
    annotations:
      brokered_service_context_spaceName: "smoke-tests"
      brokered_service_context_organizationName: "osb-cmdb-brokered-services-org-client-0"
      brokered_service_api_info_location: "api.redacted-domain/v2/info"
      brokered_service_context_instanceName: "osb-cmdb-broker-0-smoketest-1591105235"
    labels:
      brokered_service_instance_guid: "29dc53da-b853-444c-a1a6-c2e04d82e840"
      brokered_service_context_organization_guid: "c2169b61-9360-4d67-968c-575f3a10edf5"
      brokered_service_originating_identity_user_id: "0d02117b-aa21-43e2-b35e-8ad6f8223519"
      brokered_service_context_space_guid: "1a603476-a3a1-4c32-8021-d2a7b9b7c6b4"
```
