### ISSUE TITLE
Osb-cmdb smoke tests fails when testing coab-noop (i.e. add option skip probe app)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/paas-templates#831]
### Expected behavior

* As a paas-templates maintainer
* In order to test osb-cmdb support for async coab services without consumming Iaas resources
* I need to run osb-cmdb smoke tests against coab-noop with a green status

### Observed behavior
 
* When configuring osb-cmdb to use coab-noop with secret.yml

```yml
  # overview service visibility is manually managed, see paas-templates/ops-depls/cf-apps-deployments/overview-broker/README.md
  # noop-on-demand is published by its broker post-deploy. Relaunch COAB concourse job when coab-deps/TF removed it
  register_broker_services: "p-mysql noop-ondemand overview-service"
#[...]
  smoke_test_service: noop-ondemand #name of the service to instanciate in smoke tests
  smoke_test_service_plan: default    #name of the service plan to instanciate in smoke tests
```
* then the smoke test fails to skip the sample probe app with the following trace

```
-----------------------------------------------------
Probing the service:
-----------------------------------------------------
Probe invocation failed with response: 500
Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
	
Backtrace: /home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/home/vcap/deps/0/vendor_bundle/ruby/2.4.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
```

### Possible fix

Add a secret property to configure the sample app probe url to use. This is only currently configured in templates repo (eg. coab-depls/cf-apps-deployments/coa-noop-broker/template/post-deploy.sh )

```sh
#Disable use of a probe, since noop don't need them
export SERVICE_PROBE_APP_GIT_REPO_URL=""

```

### Affected releases

* v47
