### ISSUE TITLE
Leverage k8s service topology /endpointslices to reduce traffic latency

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#833]
### Expected behavior

* As a  paas-templates author
* In order to 
  - obtain best performance from k8s networking, for control plane and marketplace service access
 - avoid "hidden" hop between hosting k8s vms / iaas azs / regions
* I need 
  - to leverage k8s service topology feature
  - configure services to prefer intra az traffic (giving best performance at normal times, and smooth inter az failover)

### References
- https://v1-17.docs.kubernetes.io/docs/concepts/services-networking/service-topology/
- https://v1-17.docs.kubernetes.io/docs/concepts/services-networking/service-topology/#prefer-node-local-endpoints
- https://v1-17.docs.kubernetes.io/docs/concepts/services-networking/service-topology/#prefer-node-local-zonal-then-regional-endpoints

- https://cilium.io/blog/2020/11/10/cilium-19#vmsupport ability with cillium CNI to include any VM in a k8s cluster routing mechanism

- https://learnk8s.io/kubernetes-long-lived-connections

related: topology for storage
- https://static.sched.com/hosted_files/kccncna20/c7/Storage_Assignment_via_Pod_Scheduling.pdf

### design overview
This mechanism has much value for multi-az / multi-region deployment.
For dataplane services, we want to maximise localisation, and be able to failover (other az, other region).

k8s 1.17 has this mechanism, must be activated (done from 1.19+ by default).

The configuration is a k8 Service spec

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  topologyKeys:
    - "kubernetes.io/hostname"
    - "topology.kubernetes.io/zone"
    - "topology.kubernetes.io/region"
    - "*"
```

### Affected releases

* x.y
* earlier versions
