### ISSUE TITLE
credhub expiration alert flapping (pending, not firing)

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/paas-templates#996]
### Expected behavior

* As a paas-templates operator
* In order to 
  - be notified of credhub alerting when a certificate
* I need 
  - the related alerts to be firing to get notifications (through smtp / mattemost / sachet)

### references

latest credhub_exporter version changes scrape / cache policy (part of prometheus bosh release https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v26.3.0)

- https://github.com/bosh-prometheus/prometheus-boshrelease/pull/385 

### Observed behavior
 
When a certificate expires, the alerts are intermitent on the prometheus ui (stays PENDING, then disappear)

### Affected releases

* 48.0.2
* and earlier versions

### Traces and logs

```
#add credhub exporter
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: credhub_exporter
    release: prometheus
    properties:
      credhub_exporter:
        log_level: info
        credhub:
          api_url: https://credhub.internal.paas:8844
          client_id: director_to_credhub
          client_secret: ((/secrets/bosh_credhub_secrets))
          ca_certs: ((/internalCA.certificate))((/internalCA2.certificate))
        metrics:
          environment: ((/secrets/site))
          deployment: ((/secrets/site))

#scrape credhub exporter
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: credhub
    scrape_interval: 2h #no need to track credhub aging secrets/certs in real time
    scrape_timeout: 10m
    static_configs:
      - targets:
        - localhost:9358
```

Errros in credhub_exporter:
```
prometheus2/76422fd4-ded6-4b24-9d47-d844ae68954e:/var/vcap/sys/log/credhub_exporter# tail -f credhub_exporter.stderr.log 
time="2020-11-03T07:55:18Z" level=error msg="error while reading certificate '/micro-bosh/credhub-ha/uaa-certs'" source="collector.go:110"
time="2020-11-03T07:55:18Z" level=error msg="error while reading certificate '/micro-bosh/credhub-ha/credhub-certs'" source="collector.go:110"

```
=> due to credhub own cert manual reintegration on credhub (to benefit from alerting)
```
$ credhub get -n /micro-bosh/credhub-ha/credhub-certs
id: 92546f10-8fdf-4612-a976-972b8603b2f0
name: /micro-bosh/credhub-ha/credhub-certs
type: certificate
value:
  ca: null
  certificate: |+
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----

  private_key: |+
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

version_created_at: "2020-09-09T10:29:39Z"
```

==> missing CA (internalCA)
